### ISSUE TITLE
NoSuchMethod exception thrown on the server when trying to grow a beanstalk in multiplayer

### ISSUE THREAD

**Issue by theishiopian** [TeamTwilight/twilightforest#400] opened 2018-01-07 03:18 UTC
Forge version: forge-1.12.2-14.23.1.2562
Twilight Forest version: twilightforest-1.12.2-3.5.263-universal

Steps to reproduce: right click an uberous soil block with magic beans on a multiplayer server

What I expected to happen: a beanstalk 

What happened instead: this in the server log:

[18:41:41] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.WorldProvider.func_76571_f()F
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.WorldProvider.func_76571_f()F
	at twilightforest.item.ItemTFMagicBeans.getCloudHeight(ItemTFMagicBeans.java:47) ~[ItemTFMagicBeans.class:?]
	at twilightforest.item.ItemTFMagicBeans.func_180614_a(ItemTFMagicBeans.java:31) ~[ItemTFMagicBeans.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:852) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by Hubry** [comment] 2018-01-07 03:22
Duplicate of #382, already fixed indev (91143da412a34d5b76cfaf56a93665862a2df7c7), wait for the next build on CurseForge (no idea when will that happen).

**Comment by Tamaized** [comment] 2018-01-07 04:12
^

**Closed as completed by Tamaized** 2018-01-07 04:12 UTC
