### ISSUE TITLE
Naga being rendered crashing world. 1.20.1 FORGE

### ISSUE THREAD

**Issue by border999** [TeamTwilight/twilightforest#2027] opened 2024-04-20 23:20 UTC
### NeoForge Version

47.2.23

### Twilight Forest Version

4.3.2145

### Client Log

https://gist.github.com/border999/350c72336896a6f9e6a88b7318731938

### Crash Report (if applicable)

https://gist.github.com/border999/03e1d7b784cbd5aacd4e618704ed5b97

### Steps to Reproduce

1. Approached the lair of the Naga.
2. Presumably got close enough that the Naga spawned.
3. Game world crashes.

### What You Expected

Naga fight with no crash.

### What Happened Instead

Crashed and now can't reenter my world without instantly crashing again. I will need to attempt and edit the position of my player in order to escape otherwise, or delete the dimension data.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2024-04-20 23:20
duplicate of #2012

**Closed as completed by GizmoTheMoonPig** 2024-04-20 23:20 UTC
Labels: bug
