### ISSUE TITLE
Mist wolf causes blind effect only when suffocating

### ISSUE THREAD

**Issue by entrechienetloup** [TeamTwilight/twilightforest#1440] opened 2022-01-23 01:31 UTC
### Forge Version

37.1.1

### Twilight Forest Version

4.0.875

### Steps to Reproduce

1. Spawn mist wolf into a wall
2. Be sure to stand higher than it
3. Attack

### What You Expected

Mist wolf to cause blind effect whenever being attacked

### What Happened Instead

Mist wolf caused blind effect only when suffocating (as in the video below)

### Additional Details

https://user-images.githubusercontent.com/40696228/150661135-a93fcd5c-8fcf-4d29-a42c-83d253718615.mp4

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2022-02-04 03:20
As weird as this issue may seem, there's a very good reason as to why this is happening. 
While I was investigating the code behind this, I learned that the mist wolf checks the block brightness at its location. It only inflicts blindness if it's in a dark area. Since the mist wolf is in a block, it thinks the brightness is 0, and causes blindness, while being out in the open causes it to fail since its bright. Spawning the wolf in a cave, or the dark forest where it's supposed to live will give you the effect when it attacks. 
Closing this as it works as intended, this is just a special case

**Closed as completed by GizmoTheMoonPig** 2022-02-04 03:20 UTC
Labels: bug
