### ISSUE TITLE
Crash on mod spawn from command

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamTwilight/twilightforest#1636] opened 2022-09-16 16:36 UTC
### Forge Version

40.1.68

### Twilight Forest Version

1.18.2-4.1.1184-universal

### Crash Report (if applicable)

see Additional Details section for multiple links

### Steps to Reproduce

1. On a server, I am running CCI (Content Creator Integration) mod to produce a mount for myself and another player to be spawned under us (forcing us to mount the entity) using the SwapThings mod using this command: `/swapthings summonmount playername $user bee`
2. Be in the nether when this command is used or triggered.
3. The other player and eventually myself are both put into a state of inactivity on the server and can't effect anything. Re-logging will result in either another crash or the sudden arrival of the "mount" as described above and possibly more crashes.

### What You Expected

The players described as above to be put on a mount with no crashing or issues.

### What Happened Instead

The other player and eventually myself are both put into a state of inactivity on the server and can't effect anything. Re-logging will result in either another crash or the sudden arrival of the "mount" as described above and possibly more crashes.

### Additional Details

Crash report 1: https://gist.github.com/VallenFrostweaver/d9567c124bc855d7f3e3bf0703df7900
Crash report 2: https://gist.github.com/VallenFrostweaver/ce5f58a968fc44c9b9033a0a3a62c4d9
Crash report 3: https://gist.github.com/VallenFrostweaver/b42a18913c598de6493ea7be9ef59915

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment] 2022-09-17 07:11
After a bit of digging around, this appears to be related to #1555. The reproduction steps appear unrelated, but they also seem to draw back to a CME when trying to add item model properties. Not sure how the first two steps seem to be related, we'd need a full log to check what the cause might be, if it even is caused on our side.

It *might* be fixed in the 1.19 versions - haven't been able to reliably know because of the type of crash this is - but I'm not sure if we'd backport a potential fix as we now only support 1.19.2.

**Closed as completed** 2022-09-21 23:23 UTC
Labels: bug, duplicate
