### ISSUE TITLE
Mineshaft generating where it shouldn't.

### ISSUE THREAD

**Issue by FluffyDoom** [TeamTwilight/twilightforest#1077] opened 2021-04-12 04:35 UTC
Forge version: 1.16.5
Twilight Forest version: 4.0.426

Steps to reproduce:
1. Fly around the beginning biome of the Twilight Forest Realm.

What I expected to happen: Looking for the first boss.

What happened instead: I found a whole mineshaft just generated. Picture attached.

![2021-04-11_23 34 09](https://user-images.githubusercontent.com/82357824/114341084-8c4b4780-9b1e-11eb-9008-3346e6db74c1.png)

**Comment by TheOnlyMann** [comment] 2021-04-12 04:39
after some googling, this doesnt seem to ba a vanila structure. mineshafts only generate with oak planks, aside from badlands mineshaft which is generated with dark oak planks.
check your mod list and see if theres an another mod hindering, or spawning these mineshafts.
as for source: https://minecraft.fandom.com/wiki/Mineshaft

**Comment by GizmoTheMoonPig** [comment] 2021-04-12 04:45
Duplicate of #1039, you need to blacklist our dimension from Repurposed Structures

**Closed as completed by GizmoTheMoonPig** 2021-04-12 04:45 UTC
