### ISSUE TITLE
[1.20.4] Hollow Oak generating inside naga courtyard

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#2222] opened 2024-08-22 18:49 UTC
### NeoForge Version

20.4.235

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

1. Enter TF, navigate to coords -4901 ~ -10185

### What You Expected

Hollow oaks should not generate inside the courtyard, if our memory is correct

### What Happened Instead

A hollow oak generated in the corner of the courtyard

### Additional Details

![2024-08-22_13 48 45](https://github.com/user-attachments/assets/23d98885-b370-415b-9a9e-a1b8996e2eb3)
![2024-08-22_13 44 07](https://github.com/user-attachments/assets/6e12452c-bb7c-42f1-9d28-06a43367a2ae)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment] 2024-08-22 19:39
This is a duplicate of #2058, which has been fixed.

**Closed as completed** 2024-09-01 22:54 UTC
Labels: bug
