### ISSUE TITLE
Broken Lich Barrier Rendering

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [TeamTwilight/twilightforest#1871] opened 2023-08-24 02:06 UTC
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1809

### Steps to Reproduce

1. Launch modpack world
2. spawn in twilight forest for the first time
3. approach a lich castle 
4. 
![2023-08-23_18 35 06](https://github.com/TeamTwilight/twilightforest/assets/16616656/13735f48-526b-40e1-893e-0a35d8c2e1c5)
This happens. 

### What You Expected

Seeing the usual block barrier that generates around the lich castle. 

### What Happened Instead

![2023-08-23_18 35 06](https://github.com/TeamTwilight/twilightforest/assets/16616656/13735f48-526b-40e1-893e-0a35d8c2e1c5)

### Additional Details

4.3.1750 also has this error, when and when NOT using rubidium. <- does that count as 'optifine'? Other progression barriers are unaffected. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-08-24 02:07
duplicate of #1769

**Closed as completed by GizmoTheMoonPig** 2023-08-24 02:07 UTC
Labels: bug
