### ISSUE TITLE
Mod loading error

### ISSUE THREAD

**Issue by shortstuffmena** [TeamTwilight/twilightforest#1733] opened 2023-01-17 16:36 UTC
### Forge Version

minecraftforge:44.1.0

### Twilight Forest Version

twilightforest-1.19.2-4.2.1493-universal

### Crash Report (if applicable)

---- Minecraft Crash Report ---- // I'm sorry, Dave.  Time: 2023-01-17 16:24:35 Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.3-44.1.0-universal.jar%23202!/:?] {re:classloading} 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.3-44.1.0-universal.jar%23202!/:?] {re:classloading} 	at net.minecraft.server.Main.main(Main.java:114) ~[server-1.19.3-20221207.122022-srg.jar%23197!/:?] {re:classloading} 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.3-44.1.0.jar%2368!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2355!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: main Stacktrace: 	at twilightforest.init.TFBannerPatterns.<clinit>(TFBannerPatterns.java:10) ~[twilightforest-1.19.2-4.2.1493-universal.jar%23195!/:4.2.1493] {re:classloading} -- MOD twilightforest -- Details: 	Caused by 0: java.lang.reflect.InvocationTargetException 		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {} 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.0.jar%23199!/:?] {} 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.0.jar%23198!/:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}  	Mod File: /home/minecraft-2/server/mods/twilightforest-1.19.2-4.2.1493-universal.jar 	Failure message: The Twilight Forest (twilightforest) has failed to load correctly 		java.lang.reflect.InvocationTargetException: null 	Mod Version: 4.2.1493 	Mod Issue URL: https://github.com/TeamTwilight/twilightforest/issues 	Exception message: java.lang.NoSuchFieldError: f_235735_ Stacktrace: 	at twilightforest.init.TFBannerPatterns.<clinit>(TFBannerPatterns.java:10) ~[twilightforest-1.19.2-4.2.1493-universal.jar%23195!/:4.2.1493] {re:classloading} 	at twilightforest.TwilightForestMod.<init>(TwilightForestMod.java:96) ~[twilightforest-1.19.2-4.2.1493-universal.jar%23195!/:4.2.1493] {re:classloading} 	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {} 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.0.jar%23199!/:?] {} 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.0.jar%23198!/:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}   -- System Details -- Details: 	Minecraft Version: 1.19.3 	Minecraft Version ID: 1.19.3 	Operating System: Linux (amd64) version 5.4.0-135-generic 	Java Version: 18, Oracle Corporation 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation 	Memory: 160650864 bytes (153 MiB) / 394264576 bytes (376 MiB) up to 5918162944 bytes (5644 MiB) 	CPUs: 6 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 9 5900X 12-Core Processor 	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0 	Microarchitecture: Zen 3 	Frequency (GHz): 3.70 	Number of physical packages: 1 	Number of physical CPUs: 12 	Number of logical CPUs: 24 	Graphics card #0 name: ASPEED Graphics Family 	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03) 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: 0x2000 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 64408.07 	Virtual memory used (MB): 782.16 	Swap memory total (MB): 0.00 	Swap memory used (MB): 0.00 	JVM Flags: 1 total; -Xmx5644m 	ModLauncher: 10.0.8+10.0.8+main.0ef7e830 	ModLauncher launch target: forgeserver 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.3.jar eventbus PLUGINSERVICE  		fmlloader-1.19.3-44.1.0.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.19.3-44.1.0.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.19.3-44.1.0.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.19.3-44.1.0.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.19.3-44.1.0.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		server-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |COMMON_SET|Manifest: NOSIGNATURE 		mcw-bridges-2.0.6-mc1.19.3forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |COMMON_SET|Manifest: NOSIGNATURE 		TerraBlender-forge-1.19.3-2.1.0.134.jar           |TerraBlender                  |terrablender                  |2.1.0.134           |COMMON_SET|Manifest: NOSIGNATURE 		AmbientEnvironment-forge-1.19.3-8.0+4.jar         |Ambient Environment           |ambientenvironment            |8.0+4               |COMMON_SET|Manifest: NOSIGNATURE 		BiomesOPlenty-1.19.3-17.2.0.494.jar               |Biomes O' Plenty              |biomesoplenty                 |17.2.0.494          |COMMON_SET|Manifest: NOSIGNATURE 		mcw-roofs-2.2.2-mc1.19.3forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE 		mcw-doors-1.0.7forge-mc1.19.3.jar                 |Macaw's Doors                 |mcwdoors                      |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE 		architectury-7.0.66-forge.jar                     |Architectury                  |architectury                  |7.0.66              |COMMON_SET|Manifest: NOSIGNATURE 		mcw-trapdoors-1.0.8-mc1.19.3forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.8               |COMMON_SET|Manifest: NOSIGNATURE 		mcw-fences-1.0.7-mc1.19.3forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE 		forge-1.19.3-44.1.0-universal.jar                 |Forge                         |forge                         |44.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |COMMON_SET|Manifest: NOSIGNATURE 		twilightforest-1.19.2-4.2.1493-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1493            |ERROR     |Manifest: NOSIGNATURE 		mcw-paths-1.0.2forge-mc1.19.3.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE 		mcw-paintings-1.0.4forge-mc1.19.3.jar             |Macaw's Paintings             |mcwpaintings                  |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE 		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |COMMON_SET|Manifest: NOSIGNATURE 	Crash Report UUID: 7a70f622-87d6-484a-80c7-9d16d4eb5317 	FML: 44.1 	Forge: net.minecraftforge:44.1.0

### Steps to Reproduce

1. Downloaded twilight forest.
2. Added it to forge server
3. tried to turn server on
4. game crashed

### What You Expected

Want to be able to run twilight forest on server

### What Happened Instead

Game failed to load

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-01-17 16:38
duplicate of #1728

**Closed as completed by GizmoTheMoonPig** 2023-01-17 16:38 UTC
Labels: bug
