### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#806] opened 2019-08-18 17:51 UTC
Forge version: x.2838
Twilight Forest version: 3.9.984
Link to crash log: https://paste.dimdev.org/rumebirupe.mccrash

Steps to reproduce:
1. Attempt to launch game.

What I expected to happen:
-Game to load
What happened instead:
-Game did not load

**Comment by bs2609** [comment] 2019-08-18 17:52
Duplicate of #685

**Closed as completed by bs2609** 2019-08-18 17:52 UTC
Labels: duplicate
