### ISSUE TITLE
Worldgeneration of the Final Castle is broken

### ISSUE THREAD

**Issue by Gitcrafter** [TeamTwilight/twilightforest#1126] opened 2021-05-16 16:18 UTC
Forge version: 1.16.5 36.1.3
Twilight Forest version: 1.16.5 4.0.435
 
the generation of the final castle is broken, with some towers partly or completely missing and other structures generating on top of it, see the screenshots below for more info

![2021-05-16_18 04 02](https://user-images.githubusercontent.com/81863925/118404199-28aebf80-b672-11eb-8641-48580df8a55c.png)
![2021-05-16_18 04 25](https://user-images.githubusercontent.com/81863925/118404223-43813400-b672-11eb-8a2b-6d31d1c6a343.png)
![2021-05-16_18 04 40](https://user-images.githubusercontent.com/81863925/118404230-4a0fab80-b672-11eb-916d-f918c33d1c8f.png)
![2021-05-16_18 04 51](https://user-images.githubusercontent.com/81863925/118404234-53007d00-b672-11eb-8dfd-768baf3f6885.png)
![2021-05-16_18 05 06](https://user-images.githubusercontent.com/81863925/118404242-601d6c00-b672-11eb-844b-27f289ae618f.png)

**Comment by GizmoTheMoonPig** [comment] 2021-05-17 02:06
duplicate of #1054

**Closed as completed by GizmoTheMoonPig** 2021-05-17 02:06 UTC

**Comment by Gitcrafter** [comment] 2021-05-19 16:19
sorry, didn´t knew that
