### ISSUE TITLE
Doors icon missing

### ISSUE THREAD

**Issue by Alepod** [TeamTwilight/twilightforest#800] opened 2019-08-13 00:18 UTC
twilightforest-1.12.2-3.9.984
FML 8.0.99.99

There's missing doors, though doors itself are looking OK
![2019-08-13_03 17 19](https://user-images.githubusercontent.com/22130090/62906804-f5dae780-bd78-11e9-8f2e-0caede7a5dfe.jpg)
![2019-08-12_22 26 18](https://user-images.githubusercontent.com/22130090/62906833-1e62e180-bd79-11e9-9b3f-94683b06011b.jpg)

**Comment by Andromander** [comment] 2019-08-13 00:19
Duplicate of #711

**Comment by Tamaized** [comment] 2019-08-13 00:30
#BlameDrull

**Closed as completed by Tamaized** 2019-08-13 00:30 UTC
Labels: duplicate
