### ISSUE TITLE
[1.21.1][Neoforge] Loot table wth 177 bones breaks the game

### ISSUE THREAD

**Issue by ffuentesm** [TeamTwilight/twilightforest#2314] opened 2024-12-12 18:23 UTC
### NeoForge Version

21.1.89

### Twilight Forest Version

4.6.2941

### Client Log

https://api.mclo.gs/1/raw/MREIxPP

### Steps to Reproduce

Have EMI and EMI loot installed with TWF
Join/create a new world

### What You Expected

I should join my world

### What Happened Instead

The game can't join the world 
![image](https://github.com/user-attachments/assets/dd69ecb2-0be1-450d-a6e9-bad6d59de162)

> [minecraft/Util]: Error saving [177 minecraft:bone]. Original cause: java.lang.IllegalStateException: Value must be within range [1;99]: 177
With components:
{
	minecraft:max_stack_size=>64
	minecraft:lore=>ItemLore[lines=[], styledLines=[]]
	minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}
	minecraft:repair_cost=>0
	minecraft:attribute_modifiers=>ItemAttributeModifiers[modifiers=[], showInTooltip=true]
	minecraft:rarity=>COMMON
}

### Additional Details

emi_loot-0.7.4+1.21+neoforge
emi-1.1.18+1.21.1+neoforge
https://github.com/fzzyhmstrs/EMI_loot/issues/100

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2024-12-12 18:26
duplicate of #2301

**Closed as completed by GizmoTheMoonPig** 2024-12-12 18:26 UTC
Labels: bug
