### ISSUE TITLE
Fix Uncrafting Table Outline

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2043] opened 2024-05-03 19:25 UTC
### The Suggestion

Mimic what was done with Uberous Soil and make the outline solid

### Why Should It Be in the Mod?

This does not look nice :(

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/1249e227-eae0-41c0-95e7-73719f57f56c)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment] 2024-05-03 19:39
duplicate of #1799

**Closed as completed by jodlodi** 2024-05-03 19:39 UTC
Labels: suggestion
