### ISSUE TITLE
Missing door textures in 1.16.5 latest release

### ISSUE THREAD

**Issue by MapleSyrupMerch** [TeamTwilight/twilightforest#1289] opened 2021-09-19 15:40 UTC
Forge version: 36.2.4
Twilight Forest version: 4.0.546
Link to crash log: (no crash)

Steps to reproduce:
1. Create any kind of Twilight Forest wood into planks
2. Craft a door using a crafting table

OR

1. Open the creative menu
2. Navigate to the Twilight Forest tab
3. Look for any of the doors

What I expected to happen: Textures to appear as normal.

What happened instead: Purple and black missing texture file appeared.
![Screenshot (382)](https://user-images.githubusercontent.com/88410125/133933609-8c4ce60a-15ed-47bd-a465-c359cab1f511.png)
![Screenshot (383)](https://user-images.githubusercontent.com/88410125/133933613-d723333e-c2bf-4d38-8e2f-90860d2564c1.png)

**Comment by GizmoTheMoonPig** [comment] 2021-09-19 15:41
duplicate of #1035

**Comment by Tamaized** [comment] 2021-09-19 15:41
Duplicate #711

**Closed as completed by GizmoTheMoonPig** 2021-09-19 15:41 UTC
Labels: duplicate

**Comment by yancypro** [comment] 2022-03-05 15:20
Ok, I'm back to notify you of the same problem. I have the latest mod version (4.0.870) and I am still seeing those dreaded checkered pink & black icons for the following wooden doors: Twilight Oak, Canopy, Mangrove, Darkwood, Timewood, Transwood (Trap Door too), Minewood & Sortingwood.  I also noticed the Pink, Yellow, Blue & Violet Castle Doors are cubes. Is this correct?

![image](https://user-images.githubusercontent.com/65453692/156889476-c245cea9-49f5-4193-b28e-f09d916759b9.png)

Now I don't want to pester the Twilight Team with the same issue over and over as I have reported this back on May 16, 2020 for MC version 1.12.2 and again on May 22, 2021 for 1.16.5, but after 2 years I would have thought this would be corrected for all versions. Is there anything that I can provide you to help with this?
I love this mod and greatly appreciate the team spending their precious personal time to keep it going and growing.

**Comment by GizmoTheMoonPig** [comment] 2022-03-05 15:40
Door item textures were fixed in 1.17 since we got the textures for them in that version. We don't backport changes, so earlier versions of the game won't get these textures. If you would like to, you can grab the textures from 1.17 and make yourself a resource pack **for personal use only**. **Please do NOT redistribute a pack with the textures if you choose to do this.**

**Comment by BigClarky** [comment] 2022-11-17 18:06
same thing happens in 1.12.2

**Comment by oZeepuh** [comment] 2023-03-11 08:05
how exactly would one go about making a resource pack to fix this
