### ISSUE TITLE
[1.19.2] Twilight Forest crashes Minecraft upon launch

### ISSUE THREAD

**Issue by BlackdownPH** [TeamTwilight/twilightforest#1707] opened 2022-12-12 23:31 UTC
Forge version: 
Twilight Forest version: twilightforest-1.19.2-4.2.1468-universal
Link to crash log: (https://gist.github.com/BlackdownPH/cab55e260648318d5b69dccd2ede083f)

Steps to reproduce:
1. Install twilightforest on Forge version 43.2.0
2. Launch minecraft
3. Game crashes and produces an exit code: -1

What I expected to happen:
Minecraft would boot to the main menu

What happened instead:
The game crashed

**Comment by MarioSMB** [comment] 2022-12-15 12:55
Duplicate of #1017

**Comment by Tamaized** [comment] 2022-12-15 16:00
> Duplicate of #1017

It's not

**Comment by MarioSMB** [comment] 2022-12-15 16:03
Apologies, I had multiple tabs open and would've sworn I saw OptiFine in the title - feel free to remove my comments here!

**Comment by Tamaized** [comment] 2023-02-06 19:02
Is this still happening in [4.2.1493](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4337394)?

If so can we get a full client log, not just the crash report. Seems like the crashlog isnt giving the full story.

**Closed as completed** 2023-02-12 21:08 UTC
Labels: cant-reproduce
