### ISSUE TITLE
Boss body parts doesnt appear and a bit of other stuff

### ISSUE THREAD

**Issue by LuKzuX** [TeamTwilight/twilightforest#1058] opened 2021-04-08 00:32 UTC
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen: Boss part should be visible.

What happened instead: When i Found Naga, her body was there, but it was invisible, same occurred when i spawned the Hydra, but instead of the body, her 3 heads were invisible. The Skeleton druid is moving VERY fast too.

Some other minor stuff i think that should be improved: More mob spawning and variety (i dont know if the mob list are complete, but if it is, a bit more of fauna to the Twilight Forest would be cool.

I think some biomes aren't spawning, such the plains-like biome.

Things i would like to see in the mod: More structures in the underground and some Villages to bring a RPG feeling.

**Comment by GizmoTheMoonPig** [comment] 2021-04-08 00:34
If you have either Optifine or Entity Culling, remove those to see the bosses again. (if you dont have either of these let us know)
Skeleton druid was fixed in a recent commit. 
Every biome spawns as intended. The clearing is just rare.

**Comment by ZeroBloodedge** [comment] 2021-04-22 12:43
我也遇到了同样的情况。
主要就是娜迦没身子，九头蛇没头。
Naga's body and Hydra's head are invisible.

**Comment by Killer-Demon** [comment] 2021-05-25 01:05
@GizmoTheMoonPig already addressed this. If you have Optifine installed, that's the culprit.

**Closed as completed by Killer-Demon** 2021-05-25 01:05 UTC
Labels: other mod
