### ISSUE TITLE
Game fails to load with latest TF and latest Building Gadgets

### ISSUE THREAD

**Issue by katubug** [TeamTwilight/twilightforest#1691] opened 2022-11-25 19:03 UTC
### Forge Version

40.1.84

### Twilight Forest Version

4.1.1423

### Client Log

https://gist.github.com/katubug/76996bed33984733276b980b373e0c5f

### Crash Report (if applicable)

https://pastebin.com/kmbKQFRC

### Steps to Reproduce

1. Install Building Gadgets 3.13.1-build.18
2. Install previously mentioned Twilight Forest version
3. Attempt to launch modpack

### What You Expected

The game to load up correctly

### What Happened Instead

```
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.84-universal.jar%23287!/:?] {re:classloading}
```

### Additional Details

Issue does not occur with previous 1.18.2 version of Building Gadgets. tbh I'm not sure whether to even report this here, but this is what shows is the logs, so please let me know if I ought to report it to BG instead. Thanks!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Mrthomas20121** [comment] 2022-11-27 13:19
i'm having the same error without building gadget installed.
running forge 40.1.85. this might be an issue with the more recent 1.18.2 forge version

**Comment by GizmoTheMoonPig** [comment] 2022-11-28 05:29
duplicate of #1555 as its the same bug causing the crash

**Closed as completed by GizmoTheMoonPig** 2022-11-28 05:29 UTC
Labels: bug
