### ISSUE TITLE
Modify bosses hp?

### ISSUE THREAD

**Issue by An028** [TeamTwilight/twilightforest#637] opened 2018-10-01 11:37 UTC
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:
Can modify bosses hp
What happened instead:
i can't

**Comment by Andromander** [comment] 2018-10-01 11:39
~~Can you define what you mean by "Modify bosses hp"? Is there another mod you are using that can tweak the values of the health?~~

Disregard this message, may have replied too early.

**Comment by An028** [comment] 2018-10-01 11:39
My mods include a lot of op weapons, Kill the lich king in like 3-4 hits lol

**Comment by An028** [comment] 2018-10-01 11:40
> Can you define what you mean by "Modify bosses hp"? Is there another mod you are using that can tweak the values of the health?

I just want to set bosses hp higher in twilight forest

**Comment by An028** [comment] 2018-10-01 11:40
Iooked in the config file but can't find it

**Comment by Winstannce** [comment] 2018-10-25 16:46
> Iooked in the config file but can't find it

You can't change anything related to the entities of the mod through the Config file.

**Comment by GanthorPrime** [comment] 2018-10-29 21:12
if the problem is your game become too easy because of op weapons, maybe 'infernal mobs' cant help you.

[https://minecraft.curseforge.com/projects/atomicstrykers-infernal-mobs](url)

it includes a config file that allows you to scale vanilla and moded mobs hp and give them other 'skills' included in that mod.

the only thing is that sometimes you need to load a game with the entities to being modified so the mod cant detect them and add them to the config lists.

i use it along with twilight forest, and, i.e, add a mark to the litch to be always 'infernal' (it will have a random sets of skills like regen, reflect damage and others) and set his base hp to 400.  the Result: a truly EPIC fight against litch in a 4 players pve server with friends.   not mention that we need to equip slighty better armor than vanilla (other mods) to stand up in the battle.

**Comment by Tamaized** [comment] 2019-12-05 23:04
As it was suggested elsewhere, this mod is capable of changing any entity's health (and more):
https://www.curseforge.com/minecraft/mc-mods/in-control

Thus i'm closing this issue as in my eyes it's out of the scope of Twilight Forest.
My reasoning is why should every mod that adds an entity or two or a hundred create this massive config when all can be done by a single mod? It's tedious for one to add more config options every time a new entity is added to their mod.

**Closed as completed by Tamaized** 2019-12-05 23:04 UTC
Labels: will-implement, config
