### ISSUE TITLE
[1.12.2] Portal can spawn players in progression-restricted areas

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#205] opened 2017-10-09 17:06 UTC
Forge version: 2503
Twilight Forest version: 3.0.0
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Visit a glacier biome

What I expected to happen:
The snow texture should be normal as in vanilla snow.

What happened instead:
Getting a crazy amount of very fast moving snow particles on screen even when setting the particle to minimal in game settings.  Optifine is not involved but I do have CTM installed.  It's difficult to see from the screenshot, but imagine these snow particles moving very fast like static on the screen.

Oddly enough, going into creative mode stops the snow particles.  Going back into survival of course starts them back up again.

https://www.dropbox.com/s/4kxz3jp0g24ozl5/2017-10-09_10.02.01.png?dl=0

**Comment by Tamaized** [comment] 2017-10-09 17:11
This is intentional, it means you haven't unlocked the area in progression. You need the previous advancements.

**Comment by Killer-Demon** [comment] 2017-10-09 17:13
Not a bug.
This happens when going to areas in the progression system of which you have not completed the previous one(s).
It is to steer players into the right direction by debuffing them until they are ready for the area.

The progression system follows the main line in the Advancements menu, be sure to check that out.

**Comment by bs2609** [comment] 2017-10-09 17:15
The particle effects should possibly scale based on the game settings though?

**Comment by MokahTGS** [comment] 2017-10-09 17:15
Alright,  thanks.

**Comment by MokahTGS** [comment] 2017-10-09 17:19
I think the issue that I see is that the entry portal spawned me in that area.   Perhaps the entry portal should pick a beginner area instead so players aren't confused.

**Comment by Tamaized** [comment] 2017-10-09 17:20
That there is a bug, can you give the world seed and portal location in the overworld?

**Comment by MokahTGS** [comment] 2017-10-09 20:51
Yeah, I'll see what I can do.  World seed is -240349141328837326

**Comment by MokahTGS** [comment] 2017-10-09 23:24
Overworld Portal  X-1144 Z2636 Y67

**Comment by Tamaized** [comment] 2017-10-10 02:10
Hmmm, based on my testing this puts you **next** to the snow biome but not inside it.
![2017-10-09_19 09 27](https://user-images.githubusercontent.com/9671313/31366395-7db446bc-ad25-11e7-853f-cf1aaef51a25.png)

**Comment by MokahTGS** [comment] 2017-10-10 02:38
So when I first spawned in, I was in a tree and it was snowing like it was in the screen shot.  I was not next to the portal.  The only way I found the portal was by dying.

**Comment by thecanidcoder** [comment] 2017-10-12 00:39
I had a similar thing, albeit different enough to warrant this comment. 

Went into TF for the first time, game timed out as the dimension loaded. When I logged back in, I spawned inside the snow biome, but high up in the air. Fell to my death, and when I respawned, I was at the portal which was right next to the snow biome, but not actually in it. The death waypoint was about a minute's walk inside the biome with the slowing effect.

**Comment by Tamaized** [comment] 2017-10-12 00:43
Sounds like the same thing that happens with nether portals in vanilla, if you time out while going through one it has a chance to send you somewhere off 100 blocks or so, usually in a wall or lava within the nether upon reentering the game. No idea why this happens.

**Comment by thecanidcoder** [comment] 2017-10-12 06:08
Normally I'd agree, but the circumstances are otherwise essentially identical to @MokahTGS. Spawned high up, in the snow biome, near the portal but not next to it. Unless @MokahTGS also timed out and experienced the relocation bug, I'm inclined to think the time out is a red herring in my case.

**Comment by Tamaized** [comment] 2017-10-12 06:10
I have actually experienced the time out bug with vanilla portals sending to the exact same location before. So it's still possible it's the same bug.

**Comment by MokahTGS** [comment] 2017-10-12 14:58
It is possible that is what happened to me.  I'm not familiar enough with TW to know about the progression mechanics and so don't really know what is "normal" or not.

**Comment by thecanidcoder** [comment] 2017-10-12 21:33
I just had the same thing happen again, but with no timeout this time and in the same, already-established portal. Went in, spawned high up in the snow biome and fell to my death.

**Comment by Drullkus** [comment] 2017-11-13 17:18
Still occurring: https://www.reddit.com/r/feedthebeast/comments/7ci0vp/unlikely_twilight_forest_portal_spawn/dprc655/

> Seed is: -6003922740764184150 Coords (NW Portal Block): X -249, Y 46, Z -16 Hope this helps!

**Comment by NickdeK** [comment] 2018-03-28 20:49
Also replicated this. Below portal creation spawns me in between snow biome and swamp biome, can't go anywhere. Creating the portal at overworld spawn point seems to work just fine (spawn in a dense forest).

Minecraft: 1.12.2
Twilight Forest Version: 3.6.345
Seed: nijncraft2018
NW Portal Block: X -159, Y 65, Z: -233

**Comment by Tamaized** [comment] 2018-06-11 18:51
So what I gather after rereading all of this, this was a bug that has been fixed by a9835f4f25460a90778ac8e3ed8ef6ef34cdbaf1 where the portal was placed in the correct spot but the player themselves were sent some place else ~100 blocks away or so.

**Closed as completed by Tamaized** 2018-06-11 18:51 UTC
Labels: bug

**Comment by IdontPlayz343** [comment] 2022-07-29 07:40
This has happened to me in the Forge 1.18.2 version. I went in the portal, and it sent me to the snowy locked location. Almost killed me.

**Comment by AnkarraKM** [comment] 2023-03-20 17:17
Can someone help me?
I build a portal in 1.19.3 and when i went through I spawned in a restricted area or so I think. There was rain and it did damage to me. Can I fix this somehow or should i move my portal?

Thanks in advance.
