### ISSUE TITLE
World generation freezes server after load, sodium forge related to issue (1.16.5)

### ISSUE THREAD

**Issue by Branjoman** [TeamTwilight/twilightforest#1182] opened 2021-06-16 23:34 UTC
Forge version: 36.1.31
Twilight Forest version: 1.16.5 - 4.0.490
Link to crash log: https://paste.ee/p/mLUo2

When entering the twilight forest in a new world, soon after entering the world generation freezes entirely and the server grinds to a halt. Even attempting to quit the world causes the game to freeze at the saving world portion of shutdown - at this point the game has to be force-closed. Removing sodium forge seems to fix the issue, however it does not appear to be the sole reason behind it, as an instance using only sodium forge and twilight forest does not have the same freezing issue.

**Comment by Andromander** [comment] 2021-06-22 23:47
> Removing sodium forge seems to fix the issue

>using only sodium forge and twilight forest does not have the same freezing issue

The best I can assume here is another mod within that extensive list of mods is having worldgen issues with TF, likely bad generation. Unfortunately, there's no real telling except removing mods from the list until it stops happening. I would suggest doing a binary search with TF and Sodium Forge as the base mods, and then cutting half the mods in the list until the culprit mod is found.

**Comment by jankatdincer** [comment] 2021-06-23 18:48
> Forge version: 36.1.31
> Twilight Forest version: 1.16.5 - 4.0.490
> Link to crash log: https://paste.ee/p/mLUo2
> 
> When entering the twilight forest in a new world, soon after entering the world generation freezes entirely and the server grinds to a halt. Even attempting to quit the world causes the game to freeze at the saving world portion of shutdown - at this point the game has to be force-closed. Removing sodium forge seems to fix the issue, however it does not appear to be the sole reason behind it, as an instance using only sodium forge and twilight forest does not have the same freezing issue.

I am having the exact same problem, have you figured out which mod it is that causes the problem? I'm suspecting the Caves and Cliffs Backport, Ice and Fire, or Atum 2, but I haven't had the time to test all my mods yet.

Edit: I disabled sodium forge and enabled twilight forest, it started to work. Then I re enabled sodium and tested its features to determine which one was causing the problem. Surprisingly it just worked with all of sodium's features enabled. Maybe the mod that was causing the problem was updated or anything, because it is working without problems for me even though nothing is different.

**Comment by Mikeatron-User** [comment] 2021-07-03 03:28
I was able to resolve the issue by setting `mixin.gen` to false in sodium forge config. This option encompasses a lot of sub-features, so if someone wanted to, they could probably narrow it down more.

**Comment by Mikeatron-User** [comment] 2021-07-03 04:18
I was having the same issue and I set `mixin.chunk=false` in the forge sodium config. This seems to have resolved the issue.  I tested this by deleting the twilight forest world files and regenerating them every test. `mixin.chunk` encompasses a lot of features, so it could be narrowed down to a specific feature of chunk.

**Comment by jankatdincer** [comment] 2021-07-05 15:39
Where is the mixin.chunk=false option located? Can you tell me the exact name of the file? The only files I have related to sodium are sodium-mixins.properties and sodium-options both located in the config file.

**Comment by yezhiyi9670** [comment] 2021-07-19 23:36
quark?

Edit: Minimal mod set to reproduce is `[twilightforest, sodium-forge, quark, autoreglib]`. The issue can be fixed by removing chunk mixins from sodium.

**Comment by yezhiyi9670** [comment] 2021-07-20 09:36
> Where is the mixin.chunk=false option located? Can you tell me the exact name of the file? The only files I have related to sodium are sodium-mixins.properties and sodium-options both located in the config file.

I've seen the source code of sodium. It seems that you can just add this option if it doesn't exist.

**Closed as completed** 2022-05-25 16:21 UTC
