### ISSUE TITLE
1.16.5 classic resource pack render error

### ISSUE THREAD

**Issue by seanxiecn** [TeamTwilight/twilightforest#1453] opened 2022-03-06 06:48 UTC
### Forge Version

36.2.29

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1.change the default resource pack to built-in classic one

### What You Expected

The textures of TW turn into classic ones

### What Happened Instead

The old textures don’t fit the current models well, some go wrong when rendering

### Additional Details

The textures should be refined

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2022-03-06 06:49
duplicate of #1089

**Closed as completed by GizmoTheMoonPig** 2022-03-06 06:49 UTC
Labels: bug
