### ISSUE TITLE
Portal randomly created outside the WorldBorder

### ISSUE THREAD

**Issue by wysohn** [TeamTwilight/twilightforest#590] opened 2018-08-03 20:42 UTC
Forge version: 14.23.4.2705
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.7.424
Link to crash log: Not crash

Steps to reproduce:
1. Set worldborder with /worldborder command
2. create portal
3. sometimes the portal would created outside the region

What I expected to happen:
- It has to create portal only inside the border

What happened instead:
- portal was created outside of region

---

Border range is from -10000 ~ 10000

![image](https://user-images.githubusercontent.com/8789836/43664687-9fd45416-9722-11e8-99c6-bb5bb0a9cc08.png)

Not only it cause the player suffocation but also make chunk pre-generation useless. I will disable portal creation for now, but eventually, it would be more fun to let players build their own portal.

**Comment by Tamaized** [comment] 2018-08-03 20:44
Duplicate of #351

**Closed as completed by Tamaized** 2018-08-03 20:44 UTC
Labels: duplicate
