### ISSUE TITLE
Encountered an unexpected exception

### ISSUE THREAD

**Issue by luxlacis** [TeamTwilight/twilightforest#705] opened 2019-02-22 00:07 UTC
Forge version: 14.24.5.2768
Twilight Forest version: 3.8.689
Link to crash log: crash1: https://pastebin.com/kcUC4h7U / crash2: https://pastebin.com/qfftuBXF

Steps to reproduce:
1. Launch the game, head into the Twilight Forest, fly around and the error occurs.

What I expected to happen:
For it to not crash.
What happened instead:
It crashed.

**Comment by Andromander** [comment] 2019-02-22 00:11
Duplicate of #660 (it has been pinned). Update Forge to 23.14.5.2815.

**Closed as completed** 2019-02-22 00:37 UTC
Labels: duplicate
