### ISSUE TITLE
Twilight Forest Swarm Spider Spawner Server Crash on DW20 1.12 pack

### ISSUE THREAD

**Issue by davisschenk** [TeamTwilight/twilightforest#661] opened 2018-11-30 06:33 UTC
Forge version: 14.23.4.2760
Twilight Forest version: 3.8.689 
Link to crash log: https://gist.github.com/davisschenk/80d48b0628f7309a911db740ed10a132

Steps to reproduce:
1. Find swarm spider spawner in TF
2. Spider spawns and server crashes

What I expected to happen: The server to run fine and actually allow the server to run when spiders spawn

What happened instead: Server crashes and I have to edit my player .dat to change dimensions.

This is in DW20 1.12 mod pack

**Comment by Andromander** [comment] 2018-11-30 06:37
Duplicate of #660 I believe.

**Closed as completed** 2018-11-30 20:51 UTC
Labels: duplicate
