### ISSUE TITLE
Twilight Portal doesn't send me back to the portal in the Overworld.

### ISSUE THREAD

**Issue by mapyDayton22** [TeamTwilight/twilightforest#2047] opened 2024-05-06 13:19 UTC
### NeoForge Version

4.3.2145

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

1. Made a portal
2. Went through portal
3. Went back through portal
4. Sends me to somewhere far away from the portal

![2024-05-06_09 19 02](https://github.com/TeamTwilight/twilightforest/assets/40726888/a352a7f5-a979-4718-8290-cceb1888e5e3)
![2024-05-06_09 19 09](https://github.com/TeamTwilight/twilightforest/assets/40726888/b8762bad-9629-4f55-b535-3e35eabd95be)

### What You Expected

It sends me back to my portal

### What Happened Instead

Sends me to somewhere far away from the portal

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment] 2024-05-06 13:27
This looks like a duplicate of #1968

**Comment by jodlodi** [comment] 2024-05-11 18:13
This was in fact fixed in commit ce5c1a520de875458034a488640f6724f02503f8

**Closed as completed by jodlodi** 2024-05-11 18:13 UTC
Labels: bug
