### ISSUE TITLE
Troublesome Bug For Magic Maps

### ISSUE THREAD

**Issue by Flyer173** [TeamTwilight/twilightforest#130] opened 2017-08-06 17:46 UTC
Forge version: Dont think that counts for the bug
Twilight Forest version: Could be any EDIT: 2.4.0.111 (2.3.8dev)
Link to crash log: None

This was originally said on the Twi. Forest Discord Server! 

> VERY troublesome bug with Magic Map: If you relog and it's in a chest, it says "Unknown map" instead of the scaling information, and when you put it into your inventory, it says the scaling information BUT all of the structure icons are gone!! EDIT 2: the map still works, you just have to remap the structures and you can still see everything previously mapped only the structures disappeared

                                                              

> 

 -ZombieEnderman5 (A user on the twi forest  discord server)

**Comment by Tamaized** [comment] 2017-08-06 20:38
Might be a vanilla bug, seems to happen to the vanilla maps as well.
![2017-08-06_13 38 27](https://user-images.githubusercontent.com/9671313/29006843-9b0a82a4-7aac-11e7-84e8-df549cfcd038.png)

**Comment by Andromander** [comment] 2017-08-19 04:01
Can confirm this issue is a bug in vanilla Minecraft. https://bugs.mojang.com/browse/MC-118138

**Comment by Drullkus** [comment] 2017-08-27 05:56
Duplicate of #29

**Closed as completed by Drullkus** 2017-08-27 05:56 UTC
