### ISSUE TITLE
Upon death saved progress is lost.

### ISSUE THREAD

**Issue by SimbuTheWolfz** [TeamTwilight/twilightforest#1351] opened 2021-10-15 22:56 UTC
### Forge Version

1.16.5

### Twilight Forest Version

4.0.515

### Client Log

Latest.log

### Crash Report (if applicable)

—-

### Steps to Reproduce

Uhm so basicly i was playing with my friends on a hosted server and i suddendly died after beating the alpha yeti. I respawn and come back to get my loot but snow starts pouring down and i start taking damage for some reason. I also had this random bloke come up to me starting to assualt me physicly and then it glitched on me like i had to do the story again.

### What You Expected

Well I didnt expect heavy snow when i come back after i just killed the alpha yeti, infact its surpost to disapeer because i cleared the area before i got there. And even that i started to take damage randomously.

### What Happened Instead

I took damage from the heavu snow and a random minion come up to me with a paper.

### Additional Details

Well im on phone rn so i cant rlly, plus it was ages ago when it happened. But you can ask my friends if you want.
If you beed to contact me via discord my username is Boris Johnson#8382

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment] 2021-10-19 03:30
I don't get how this could happen, and I can't reproduce it. Closing for now but please update your version of TF to the latest and try reproducing the issue. If you manage to reproduce then comment here with any more detailed steps of how, and all of the mods the server has

**Closed as completed by Drullkus** 2021-10-19 03:30 UTC
Labels: bug

**Comment by Tamaized** [comment] 2021-10-19 10:13
This would mean your advancements got reset. Which TF can't do. Either some other mod is doing something really jank or a potential vanilla/forge bug.
