### ISSUE TITLE
Random crash while exploring

### ISSUE THREAD

**Issue by ToastyTheCoder** [TeamTwilight/twilightforest#1732] opened 2023-01-16 22:11 UTC
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1468

### Client Log

https://gist.github.com/ToastyTheCoder/9656801d16ef10215c0cd43f907c6a8e

### Crash Report (if applicable)

https://gist.github.com/ToastyTheCoder/1c424e3b6917c3d58aae7ca2e58487e7

### Steps to Reproduce

1.Booted up the server
2. 4 players online 
3. all went into the dimension 
4. played around for ~5min until the server crashed
5. rebooted 
6. we all try to join 
7. 2nd crash 
8. we join one at a time
9. works for 3 of us, until one person joins and it crashes 
10. reboot 
11. that person joins first 
12.  we manage to all get online
13. more exploring
14. 3rd crash
15. we try to all join one by one 
16. first join - crash

### What You Expected

to not crash

### What Happened Instead

crash

### Additional Details

Server side mods
![image](https://user-images.githubusercontent.com/76891033/212772641-21f5a6a3-7e96-4d5f-a25a-ca527e6486c8.png)
Client-side mods
![image](https://user-images.githubusercontent.com/76891033/212772716-e958f8ea-870e-415b-a8ee-b3a743589ac0.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-01-16 22:12
duplicate of #1699

**Closed as completed by GizmoTheMoonPig** 2023-01-16 22:12 UTC
Labels: bug
