### ISSUE TITLE
Crash launching custom modpack

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#702] opened 2019-02-05 22:19 UTC
Forge version: 2811
Twilight Forest version: twilightforest-1.12.2-3.9.851-universal.jar
Link to crash log: https://paste.dimdev.org/obunonipel.mccrash

Full mod list: https://pastebin.com/axSwT9mU

**Comment by Andromander** [comment] 2019-02-05 22:31
Duplicate of #685. Not a Twilight Forest issue.

**Closed as completed** 2019-02-05 23:03 UTC
Labels: duplicate
