### ISSUE TITLE
Wrong model of Knight Phantom Trophy

### ISSUE THREAD

**Issue by uhloin** [TeamTwilight/twilightforest#1966] opened 2024-01-06 22:01 UTC
### Forge Version

forge-1.20.1-47.1.81-installer.jar

### Twilight Forest Version

twilightforest-1.20.1-4.3.1893-universal.jar 

### Steps to Reproduce

Place Knight Phantom Trophy on any block. 

### What You Expected

Model in the inventory has normal view with horned helm, similar model in the world is expected

### What Happened Instead

Model in world is like bald bloody skull

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2024-01-06 22:04
Duplicate of #1531

**Closed as completed by GizmoTheMoonPig** 2024-01-06 22:04 UTC
Labels: bug
