### ISSUE TITLE
No land 

### ISSUE THREAD

**Issue by bob0bob** [TeamTwilight/twilightforest#241] opened 2017-10-15 19:52 UTC
Please close.    It just took forever to load,  after another 2 mins, the land and everything appeared.  

Twilight Forest version: 3.1.128
I just went through the  portal and when it said it was done loading this is what appeared.  Can't move, or anything.  

![2017-10-15_14 49 48](https://user-images.githubusercontent.com/30982580/31588516-69f40328-b1b8-11e7-9fc7-40d29f6114b1.png)

**Comment by Tamaized** [comment] 2017-10-15 19:54
looks to me like it's still in the generation process

**Comment by bob0bob** [comment] 2017-10-15 19:57
Is this normal
![2017-10-15_14 57 13](https://user-images.githubusercontent.com/30982580/31588550-32ccb88a-b1b9-11e7-9092-60200e05a3b7.png)

**Comment by Tamaized** [comment] 2017-10-15 19:58
looks to be you're in a restricted biome before you've unlocked it via advancements

**Comment by bob0bob** [comment] 2017-10-15 20:05
I read about that and it talked about stuff preventing you.  There was not a description that I under stood that would indicate what it was suppose to look like.

**Comment by williewillus** [comment] 2017-10-16 22:26
so it's a dupe of #205

**Closed as completed by williewillus** 2017-10-16 22:26 UTC
