### ISSUE TITLE
Trophy animation in inventory of JEI lags FPS, please, add option to switch it off

### ISSUE THREAD

**Issue by vgrynch** [TeamTwilight/twilightforest#1878] opened 2023-09-06 15:59 UTC
### Forge Version

43.2.21

### Twilight Forest Version

4.2.1518

### Steps to Reproduce

Trophy animation in inventory or JEI lags really bad. Rubidium-based graphics, no shaders.

### What You Expected

No lag, or option available to switch animation off.

### What Happened Instead

TPS drops from 70-80 up to 2-3 FPS when open JEI with trophy items or have trophy item in opened inventory or have it on the tools bar inventory.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-09-06 16:03
the rotation itself isnt the issue, the issue is actually rendering the heads. This has been fixed in more recent versions

**Comment by vgrynch** [comment] 2023-09-06 19:21
Can this fix be applied to 1.19.2 as well?

**Comment by GizmoTheMoonPig** [comment] 2023-09-06 19:52
we don't work on 1.19.2 anymore

**Comment by vgrynch** [comment] 2023-09-07 06:34
Any way to just stop animation (via resource pack or data pack)?

**Comment by GizmoTheMoonPig** [comment] 2023-10-02 17:57
you can remove the special item rendering by changing the item model jsons to not use `builtin/entity` as the parent using a resource pack. This will also allow you to assign any texture to the item, so you can just render the backboards if you wish or something else entirely.

**Closed as completed by GizmoTheMoonPig** 2023-10-02 17:57 UTC
Labels: bug
