### ISSUE TITLE
Suggestion to help with spawn mechanics and progression

### ISSUE THREAD

**Issue by GalaxyMoonlite** [TeamTwilight/twilightforest#1547] opened 2022-07-04 16:23 UTC
An issue ive always felt this mod had was with biome generation and how it relates to progression, the main issue id like to address is on the matter of portal generation.

With the current system it’s all too easy to spawn in deep a fire swamp or dark forest and have your experience ruined by poor biome luck, i propose to offload portal generation to a structure which only spawns in beginner biomes which contains the naga courtyard or the enchanted forest  with the quest ram.

A freshly built portal would hook to the nearest portal structure relative to coordinate conversions, and going back through the portal would send you to your spawn point like the post-dragon portal.

**Comment by Tamaized** [comment] 2022-07-04 17:25
The Teleportation code actually checks to see if you're in a safe biome, but it's possible to not locate a safe biome in its scan radius and will plant you in an unsafe biome.

A proposed solution is here and this is most likely what will be implemented.
https://github.com/TeamTwilight/twilightforest/issues/1459#issuecomment-1075866697

Closing as it's essentially a duplicate of the linked issue.

**Comment by PraseodymiumSpike** [comment] 2022-07-04 17:26
It could also translate all the coordinates so the first portal made ends up near a Naga kind of how the Nether dilates all the coordinates.

**Closed as completed by Tamaized** 2022-07-04 17:25 UTC
