### ISSUE TITLE
[1.12.2] Crash While Initializing Mods

### ISSUE THREAD

**Issue by PulseBeat02** [TeamTwilight/twilightforest#694] opened 2019-01-22 00:15 UTC
**Simple Description of What Happened**
Forge crashed while initialization of mods. 

**Forge version: 14.23.808
Twilight Forest version: 3.9.851
Link to crash log: https://paste.dimdev.org/eqapivujez.mccrash**

**What I expected to happen:**
I expected forge to start the modpack normally, initializing mods, etc.

**What happened instead:**
Forge crashed, giving off an error saying it was "unknown". Because the crash had something to do with The Twilight Forest, I decided to report the error to you.

**What I have found strangely:**
When I was loading my modpack, with the latest version of Twilight Forest (3.9.851) the modpack crashed, however, if I use a version earlier (3.8.689), it doesn't crash. Considering it was an alpha build, were there any pieces of code that were bugged?

**Comment by bs2609** [comment] 2019-01-22 00:17
Duplicate of #685

**Closed as completed by bs2609** 2019-01-22 00:17 UTC
Labels: duplicate
