### ISSUE TITLE
Dark Forest Loot Chests are Empty with Quark Installed

### ISSUE THREAD

**Issue by jahess-it** [TeamTwilight/twilightforest#1116] opened 2021-05-05 05:34 UTC
Minecraft version: <b>1.16.5</b>
Forge version: <b>36.1.16</b>
Twilight Forest version: <b>4.0.435</b>
Quark version: <b>r2.4-311</b>

### List of mods installed (with version numbers)
* AutoRegLib-1.6-47
* BlockArmor-2.6.1
* citadel-1.6.2
* curios-forge-4.0.5.1
* Easymagic-v1.0.2
* EffectEnchantments_MC_1.16.4_Vers.1.1.5
* EpicFightMod-3.2.2
* gravestone-1.0.6
* jei-7.6.4.90
* luckyblock-1.16.5-1
* Mantle-1.6.92
* Mr. Crayfish's Furniture Mod v7.0.0-pre19
* Mr. Crayfish's Vehicle Mod 0.45.2
* NetherPortalFix-7.2.1
* obfuscate-0.6.1
* Patchouli-1.16.4-50
* polymorph-0.24
* Quark-r2.4-311
* rats-7.1.1
* secretrooms-1.0.1
* Sneakyagic-v1.3.2
* sophisticatedbackpacks-2.4.0.259
* SpartanMetals-v2.1.1
* SpartanWeaponry-2.1.0-beta4
* TConstruct-3.0.3.136
* twilightforest-4.0.435 (obviously)

Link to crash log: [https://gist.github.com/jahess-it/9ff9ac8b11d8d65b30d84f0f4c14c729](https://gist.github.com/jahess-it/9ff9ac8b11d8d65b30d84f0f4c14c729)

### Steps to reproduce:
1. Go to Twilight Forest dimesion.
2. Go to the Dark Forest biome.
3. Find a loot chest.
4. Open it.

### What I expected to happen:
Loot chest should have loot in it when opened.

### What happened instead:
Loot chest is empty when opened. Interestingly enough, loot chest drops its contents without error if broken before it is opened.
<hr />

Let me know if there is anything else you need. Thank you for your time.

**Comment by Andromander** [comment] 2021-05-25 10:15
This issue doesn't appear to be caused by TF.
From what it looks like, if the chest is opened, there is an error from quark related to something called "blockArmor"? There's a few things that appear to be throwing me off trying to read that crash log. Might I suggest trying out TF version 4.0.467? Two of our unused enchantments were removed in that version. If it doesn't, I would say this is an issue for quark.

**Comment by Hubry** [comment] 2021-05-25 10:28
Looks like Block Armor expects `context.get(LootParameters.TOOL)` to always return something [here](https://github.com/2piradians/Block-Armor/blob/902856b3e16fcf493a8e85a7d6dbbfe38290912f/src/main/java/twopiradians/blockArmor/common/seteffect/SetEffectAutoSmelt.java#L137) despite the method being marked as nullable.
Vanilla `EnchantmentHelper#getEnchantments` also calls `ItemStack#getItem` without a null check just like Quark does, so I would say this is purely Block Armor's fault. Are you wearing some of their armor?

**Comment by Killer-Demon** [comment] 2022-05-27 13:04
Since there hasn't been any further communication we'll be closing this. If the issue persists feel free to update and re-open this issue.

**Closed as completed by Killer-Demon** 2022-05-27 13:04 UTC
Labels: other mod
