### ISSUE TITLE
Stronghold Progression Bug

### ISSUE THREAD

**Issue by marc-himmelberger** [TeamTwilight/twilightforest#708] opened 2019-03-04 20:43 UTC
Forge version: 14.23.5.2772
Twilight Forest version: (this is the build number) 3.8.689

(Playing FTB Direwolf20 Pack on MC 1.12.2)
I can't seem to get the Stronghold to work for me. In creative I have no problems but in survival the game doesn't seem to register that I should be allowed to enter.
No chat message appears and I experience no blindness.

I've followed the advice in "Notes on a stronghold" (the treasure chest that spawned after I killed the boss in creative kept spawning goblins holding the book that I of course was unable to kill in survival to get the book) to the best of my ability.

Am I missing something?
Screenshots attached

Steps to reproduce:
1. Kill Naga
2. Kill Lich
3. Kill Mineshroom, drink Stroganoff
4. Kill Hydra
5. Place Hydra or Naga trophy on Stronghold pedestal
6. Enter the stronghold

What I expected to happen:
- Mobs to be killable
- The advancement for "Trophied Chamion" to unlock

What happened instead:
- Mobs inside were invincible (green particles on hit)
- The advancement doesn't unlock, no matter the trophy I place upon the pedestal - the entrance, however, does open up
- Blocks are not breakable inside the stronghold

![entrance](https://user-images.githubusercontent.com/8556523/53761679-6d514480-3ec6-11e9-836d-1d6295b10f5c.png)
The entrance
![advancements](https://user-images.githubusercontent.com/8556523/53761678-6d514480-3ec6-11e9-8ae3-254a140eade8.png)
My Advancements after placing the trophy
![particles](https://user-images.githubusercontent.com/8556523/53761682-6d514480-3ec6-11e9-9bc3-0c405f9cb396.png)
The invincibility particles

**Comment by Steamoonkie** [comment] 2019-03-20 08:57
Not sure but shouldnt you actually place another 4 heads around pedestal? I am always placing Naga, Aurora, Lich, Hydra to enter Knight Dungeon. I am surprised it opened lol :-D

**Comment by marc-himmelberger** [comment] 2019-03-20 11:12
Oooh, you mean next to the faces of the pedestal? That would explain the trophy icons that appeared on the faces. I did find it weird that they didn't match what I put on top.
I will try your suggestion and leave a comment here when I have.

**Comment by Steamoonkie** [comment] 2019-03-20 14:27
Yeah, will do. I also do not see Advancement made [Advancement for opening Knights Tomb]

**Comment by marc-himmelberger** [comment] 2019-03-20 19:17
I tried placing all the trophies you mentioned around the pedestal (and another Naga on top). But I still get the same green particles. I placed the first Naga trophy on top before the other trophies (because the pedestal sides were blank before) in case that makes a difference...

![2019-03-20_20 08 07](https://user-images.githubusercontent.com/8556523/54712165-f4035400-4b4b-11e9-941e-deee7b55a958.png)

In other news: I did figure out that you could obtain the "Notes on a Stronghold" from the goblin by dropping down through the opened portal, building a stair back up (careful, as you can't remove blocks you place) then luring the goblin back up and kill him once he's above the portal. Although I still think that's rather too complicated.

I would be happy to try any other suggestions

**Comment by Lorantine** [comment] 2019-03-20 22:30
it's been a couple years since I've played Twilight Forest (or Minecraft at all), but it's always been that you just have to put 1 trophy on top of the pedestal
once you do that, you can enter the stronghold, you get the achievement etc.
since you say that doesn't work, it's bugged (it makes no sense why you'd have to place trophies next to the pedestal anyway)

**Comment by Tamaized** [comment] 2019-03-20 23:08
It is one trophy of any type on top of the pedestal.

As for why your advancement is bugged... I'm not entirely sure.

**Comment by marc-himmelberger** [comment] 2019-03-21 19:45
I should probably note that I have been having trouble with advancements in general ever since starting with the DW20 pack. They usually appear only once the world is reloaded or only on the second try.

Maybe disabling the protective spell is tied to the advancement for the pedestal which in turn doesn't trigger upon placing the trophy because... reasons?

It's a shame really because I enjoy modded minecraft a lot and would like to advance through Twilight Forest :/

I've found this issue that sounds pretty similar to mine: [Issue #95 @ FTB-Presents-Direwold20-1.12](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/issues/95)

Could that be the cause? Should I follow up over there since it seems to be a more general problem? I've mainly posted here because it's just always worked with other mods after reloading the world.

**Comment by Tamaized** [comment] 2019-05-09 22:51
So is this confirmed to be an issue with DW20 specifically or with TF? Does it work with Twilight Forest alone?

**Comment by Abuserr** [comment] 2019-05-23 23:55
> 
> 
> So is this confirmed to be an issue with DW20 specifically or with TF? Does it work with Twilight Forest alone?

It must be the mod itself. Same problem on Enigmatica 2 Expert.

**Comment by Andromander** [comment] 2019-05-24 00:09
Did you verify that this issue exclusively occurs with Twilight Forest (no other mods present)? Also, as far as I am aware, this issue may have been resolved in version 3.9.888. Mind checking if that does not work, too?

**Comment by marc-himmelberger** [comment] 2019-06-26 11:17
I've meant to check for a long time now but since I stopped playing after the bug, it not worth it for me to investigate further.
If someone else has the problem and time, you're welcome to continue this thread

**Comment by CptEntropy** [comment] 2019-09-07 18:31
Exatly same issue here, no solution... I killed all bosses before stronghold, used Hydra Trophy for opening. I cannot do any damage and cannot break any blocks, it's like I am in the stronghold but it's not opened... When I did Goblin stronghold in Creative it didn't count for advancements, so I cannot progress  TF unfortunatly... Someone has any solution? 

 Minecraft 1.12.2, Tekxit 3 (v0.96), Twilight forrest 3.9.984

**Comment by ElevatorMusicc** [comment] 2020-10-16 06:36
i recently had this issue and found a solution that worked, so i thought id make an account and give my method in case anybody else needs it like i did! the game refused to give me the achievement for placing the trophy on the pedestal, which stopped the progression. i tried a lot of different things, (fighting bosses again, trying different trophies) but eventually i decided to go into creative and destroy and replace the pedestal in the exact same spot. it mightve been a lucky break but when i went back into survival and placed the trophy i got the achievement and could progress. hopefully this works for anyone else having this issue!

**Comment by Tamaized** [comment] 2022-05-25 15:47
Doesn't appear to be an issue in the 1.18 builds

**Closed as completed by Tamaized** 2022-05-25 15:47 UTC
Labels: progression

**Comment by Th3Chill** [comment] 2025-08-15 21:30
Here in 2025, still seems bugged.  I too have beaten the same bosses (in addition to the ice queen) and gotten the same advancements. Stronghold shield opens, but the barrier around the stronghold does not, keeping me from attacking or breaking any blocks. I doubt they'll patch it since this is an older version of minecraft, just thought I'd say something so if someone else is having this problem they will know that it's not just them doing something wrong.

Also playing on the FTB Direwolf20 Pack on minecraft 1.12.2, twilight forest version is 3.11.1021
