### ISSUE TITLE
Scepter of Life Draining won't repair

### ISSUE THREAD

**Issue by meliornox** [TeamTwilight/twilightforest#391] opened 2017-12-28 08:36 UTC
Forge version: 1.12.2-14.23.1.2575
Twilight Forest version: (this is the build number) 1.12.2-3.5.263-universal
Link to crash log: (please use a paste site such as gist, do not attach the .txt or paste the log inline) Doesn't produce a crash

Steps to reproduce:
1. Drain Scepter of Life Draining
2. Place in crafting table or inventory crafting with Fermented Spider Eye

What I expected to happen: Receive a repaired item

What happened instead: No crafting result, though JEI does show the recipe

**Comment by williewillus** [comment] 2017-12-29 02:51
can't reproduce: https://i.gyazo.com/f9cfb9f970250df1e82508eb4c3ddc6a.png

**Comment by meliornox** [comment] 2017-12-29 03:32
Cropped screenshot: https://imgur.com/a/iVu2F
Playing FTB Revelation 1.0.0, it might be another mod

**Comment by meliornox** [comment] 2017-12-29 03:57
Tested with the Zombie Scepter and the Scepter of Twilight, the former recharges and the latter will not, although again JEI says they all should.

**Comment by Tamaized** [comment] 2018-01-29 23:33
fixed in 6e29110332b4770e5386e2c402a012f6f28b8b98

**Closed as completed by Tamaized** 2018-01-29 23:33 UTC
