### ISSUE TITLE
Twilight Forest Swarm Spider no access to class

### ISSUE THREAD

**Issue by KinfThaDerp** [TeamTwilight/twilightforest#693] opened 2019-01-20 10:30 UTC
Forge version: forge-1.12.2-14.23.5.2805
Twilight Forest version:  twilightforest-1.12.2-3.8.689-universal
Link to crash log: [link](https://gist.github.com/KinfThaDerp/4b17f85a38c36bde1376e20a65ea7fce)

What I expected to happen:
Twilight Forest loading normally with all it has in it for my friend who got on the server earlier than I did
What happened instead:
the server crashed

A similar issue happened too when i was using Primitive Mobs, do you have any idea what is causing this?

**Comment by Andromander** [comment] 2019-01-20 10:41
Duplicate of #660. The issue is caused by the Spiders trying to access a normally private class (which is made public by Forge), but OpenJ9 seems to prevent the class transforming.

**Comment by KinfThaDerp** [comment] 2019-01-20 12:24
Would changing from OpenJ9 help? Or would it cause more issues somehow? I'd really like for my [server](https://cdn.discordapp.com/attachments/399585461229584384/536520924435054595/unknown.png) to actually work

**Comment by Andromander** [comment] 2019-01-20 12:25
Yeah, if you can change it from OpenJ9, it should resolve this issue.

**Comment by noobanidus** [comment] 2019-01-20 12:28
Oracle JRE is preferred as much as possible. Depending on the server and what kind of access, you might need to manually specify that you want to use non-free binaries.

**Closed as completed** 2019-01-20 15:20 UTC
Labels: duplicate
