### ISSUE TITLE
Aurora Castle Crash

### ISSUE THREAD

**Issue by Chubrel** [TeamTwilight/twilightforest#2117] opened 2024-06-08 08:40 UTC
### NeoForge Version

Forge 43.3.13

### Twilight Forest Version

4.2.1518

### Client Log

https://gist.github.com/Chubrel/ff101db6a048bf082e329721995fa4d8

### Crash Report (if applicable)

https://gist.github.com/Chubrel/2c6d36a24d30d2c5f28be13430d49e52

### Steps to Reproduce

Player looted Aurora Castle

### What You Expected

I expected that server won't crash

### What Happened Instead

Server crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment] 2024-06-27 09:39
At first glance, it seems the problem is caused by improvable skills mod. Can you provide us detailed steps to reproduce, please?

**Comment by Chubrel** [comment] 2024-06-27 10:44
I don't really sure, what it caused, but I think, it happened when player got hit by projectile (ice snowball, and, later I have seen [similar crash with slime blob](https://gist.github.com/Chubrel/21442ebe7c0c647548ebb2d38b0643d1))

**Comment by Sleepy-Horse** [comment] 2024-06-27 14:23
Ok, I kinda understood what happened here. However, your version is old (1.19.2) and unsupported. If you really wish, I can provide you custom patched version for 1.19.2.

**Comment by Chubrel** [comment] 2024-06-27 14:44
Thanks, I don't really need it. I'm glad I could help.

**Comment by Sleepy-Horse** [comment] 2024-06-27 14:49
This bug is already fixed in 1.21, by the way. Could you close the issue, please?

**Closed as completed** 2024-06-27 14:51 UTC
Labels: bug
