### ISSUE TITLE
Naga spawning in Overworld in normal vanilla biomes

### ISSUE THREAD

**Issue by Gunner76th** [TeamTwilight/twilightforest#913] opened 2020-08-06 21:41 UTC
Forge version: 
Twilight Forest version: (this is the build number) twilightforest-1.12.2-3.10.1013-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
Not applicable as it is not a crash, but rather a possible mod conflict issue. 

Steps to reproduce:
1) Install version 1.39 of the Roguelike Adventures and Dungeons modpack from Curseforge: https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

2) Create a world, and then explore. The frequency with which it happens seems to be random. 

3) I do not know if this will help replicate the issue, however please try using Seed: -4403913139813209694

4) Once the world is created using the Seed in step 3, proceed to the coordinates at X: -1387 Z: 1059

What I expected to happen: We expect a world to be generated like normal, with TLF boss mobs NOT spawning in the overworld or any other dimension. 

What happened instead: World are being generated as normal, however TLF Boss mobs (specifically the Naga so far) are being spawned outside of the TLF Dimension. 

Included is a copy of one of the user's latest.log file who is experiencing this issue. This log file belongs to the world created with the Seed listed in step 3. If there is anything else you require, please let us know. You can also come to Dreams01's Discord to speak with us directly regarding this issue by using this link: https://discord.gg/ZsrYtDb
[latest (15).log](https://github.com/TeamTwilight/twilightforest/files/5038146/latest.15.log)
Log was not posted as a Gist as Gist has been having issues recently.

**Comment by Tamaized** [comment] 2020-08-06 21:51
Definitely another mod doing this, not an issue from our side of things

**Comment by Gunner76th** [comment] 2020-08-06 22:02
Which is why I have presented this here, so that you can help identify WHY this is happening. We have checked the OTG files, and I am not seeing any references to anything there. I was hoping since you work on the code, you might have a better understanding of how it works, and possibly notice something happening while trying to recreate the issue with the steps above that would point to the cause.

**Comment by Tamaized** [comment] 2020-08-06 22:04
Have you even attempted doing a conflict search such as a binary mod removal search...

Remove mods until the issue is gone, track down the exact mod doing this.

**Comment by Tamaized** [comment] 2020-08-06 22:10
Another thing you could have tried, replicate this in peaceful to see if it's the spawner block itself being placed as those won't trigger in peaceful. If this is the case then some mod is placing our block. That could also help with a lead to whatever mod.

Our mod doesn't even add any of our bosses to any biome spawn list. Some mod is deliberately using our block or entities. There's no way for me to know and I'm not going to download an entire pack to do a removal search when you guys could 😛

**Comment by Gunner76th** [comment] 2020-08-06 22:14
After some initial online research, I came across these issues related to biome problems between TLF and OTG/Biome Bundle. Since the biome involved (to my knowledge) with the issue we are seeing is almost exclusively the Forest, and if memory servers, the Naga Arena is spawned in TLF Forest areas, it feels like this might be related at some level. 

https://github.com/PG85/OpenTerrainGenerator/issues/76
https://github.com/BiomeBundle/BiomeBundle/issues/105
https://github.com/BiomeBundle/BiomeBundle/issues/154

**Comment by Gunner76th** [comment] 2020-08-06 22:15
Again, not saying this IS but its giving me an idea on places to start with. It's already been documented in the past that OTG/Biome Bundle and TLF have had issues with each other.

**Comment by Tamaized** [comment] 2020-08-06 22:21
OTG issue is completely unrelated and closed for that matter.
Ok biome bundle, sounds like it's their issue, ok! Remove mod, issue gone? Good! Go bug that dev to fix it! Not solved? Uh oh time to start searching for the actual mod at fault then bug them 🤔 

I'm telling you now, there's nothing in our code that could be causing this that we can fix from our side of things.

**Comment by Tamaized** [comment] 2020-08-06 22:24
~~Oof they're closed source so I can't even do actual digging into their code without decompilation and using BON2~~

Wait this is an OTG add-on 🤔

**Comment by Gunner76th** [comment] 2020-08-06 22:29
As a start, I am testing just TLF, OTG/Biome Bundle on forge 2854. With the evidence so far, that seems like a logical place to start. At the moment I am not encountering any Naga spawning. I used the Seed above, went to the location, and I am using all of the configs from RAD for testing. So far nothing is happening. At the moment, it looks like its not OTG/BB causing this, but it could be that I need to wait a bit, perhaps for nightfall.

**Comment by Gunner76th** [comment] 2020-08-06 23:03
Ok, so after some further review and consult with some of our helpers, it seems the issue was not present in 1.38 but started in 1.39. This helps isolate the issue from a list of 138 mods down to 38, since that is how many had updates between the 2 versions. 
If anything in this change log jumps out at you as a possible culprit please let us know. https://pastebin.com/raw/P2FXPsH6

**Comment by Gunner76th** [comment] 2020-08-06 23:39
https://github.com/PG85/OpenTerrainGenerator/issues/339

So just discovered this issue. While RAD does not have Mo 'Creatures in the modpack (and neither did the author's list in his original post) it looks like this is pointing towards the cause. Now, while RAD is using V6 of OTG, I am curious if this issue is not also in that version as well, and was only reported for V8 as that is the most current. 

>When the issue is present, in OTG worlds mod mobs can spawn as other mod's mobs if that other mod's mob shares the same or similar name. The biggest example of this is with mowzies mobs naga being replaced by twilight forest naga

**Comment by Gunner76th** [comment] 2020-08-06 23:40
If this is the case, then it literally means that the issue can only be reproduced by loading up the registered entity list on pack load, and that testing by traditional means of testing each mod separately would never work. I am going to load a standard RAD instance, and use the /otg commands mentioned and see what it replies with.

**Comment by Gunner76th** [comment] 2020-08-06 23:50
![image](https://user-images.githubusercontent.com/5566872/89593647-ac06cf00-d81d-11ea-927c-e1e5d00f2d26.png)
And this confirms the issue, it IS OTG causing the problem as reported in the post above. When in the Overworld, in certain biomes (Stone Beach for instance) OTG is calling the EntityTFNaga instead of the EntityNaga from Mowzie. 

So either we have to wait for this to be fixed and released in V9 of OTG, or see if there is a way that TLF can encase the Naga and other boss mobs in such a way that no other mod can call them. Is that even possible within the limitations of java code?

**Comment by Tamaized** [comment] 2020-08-06 23:51
Not possible on our end.

**Comment by Tamaized** [comment] 2020-08-06 23:52
Here's the stupid thing, entity registry names have a namespace, how does a mod fuck up that badly.

**Comment by Gunner76th** [comment] 2020-08-06 23:54
I don't know, but as you can see, OTG can and is.

**Comment by Gunner76th** [comment] 2020-08-06 23:56
But at least now the different documentation related to this, as well as the ultimate cause is in a single thread. I only happened to stumble upon that issue on OTG by accident while doing various Google searches, and it had not shown up before. Thank you for help, and hopefully we can figure out a way to deal with this until OTG fixes their code.

**Comment by Gunner76th** [comment] 2020-08-06 23:57
![image](https://user-images.githubusercontent.com/5566872/89594125-05233280-d81f-11ea-985f-f220befad791.png)
And as expected OTG did in fact spawn in the wrong naga.

**Comment by Andromander** [comment] 2021-05-25 01:27
Closing as it is an OTG problem, and also should no longer happen in 1.16.

**Closed as completed by Andromander** 2021-05-25 01:27 UTC
Labels: other mod
