### ISSUE TITLE
Naga crash

### ISSUE THREAD

**Issue by PlatinumBoi03** [TeamTwilight/twilightforest#2026] opened 2024-04-14 20:05 UTC
### NeoForge Version

47.2.17 (Forge)

### Twilight Forest Version

4.3.2145

### Client Log

https://gist.github.com/PlatinumBoi03/b3b0a20c644f7a3f3676173e2f9515e8

### Crash Report (if applicable)

https://gist.github.com/PlatinumBoi03/e897849826989a810995334ccc5acacb

### Steps to Reproduce

1. Open the game
2. Create a world
3. Summon the Naga (instantly crashes)

### What You Expected

The Naga was supposed to spawn as soon as I entered the courtyard.

### What Happened Instead

The Naga spawned and the game instantly froze then crashed.

### Additional Details

If you try to reopen the world where the crash happened after, it will crash the game as soon as you open the world.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2024-04-14 20:06
duplicate of #2012

**Closed as completed by GizmoTheMoonPig** 2024-04-14 20:06 UTC
Labels: bug
