### ISSUE TITLE
Goblin knight has no lower part when natural spawn.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#246] opened 2017-10-17 00:32 UTC
Forge version: 2501
Twilight Forest version: 3.1.143

Steps to reproduce:
1. Fighting inside the maze.

What I expected to happen:Goblin knight has lower and upper part when natural spawn.

What happened instead:But goblin knight has no lower part.

**Comment by Andromander** [comment] 2017-10-17 00:33
This is an issue based on a vanilla bug where spider jockeys cannot spawn naturally

**Comment by Tamaized** [comment] 2017-10-17 00:37
#135

**Comment by Drullkus** [comment] 2017-10-17 07:42
Duplicate of #135 as @Tamaized said

**Closed as completed by Drullkus** 2017-10-17 07:42 UTC
Labels: duplicate
