### ISSUE TITLE
I Have Absolutely No Idea What is Going on. (1.16.5)

### ISSUE THREAD

**Issue by chasr34** [TeamTwilight/twilightforest#1422] opened 2021-12-21 00:16 UTC
### Forge Version

36.2.4 up to the most recent version, 36.2.22

### Twilight Forest Version

4.0.546 and a version under, 4.0.515

### Client Log

https://gist.github.com/chasr34/c7b0c9b7bf0c0daf968ed30a9b8990f3

### Crash Report (if applicable)

https://gist.github.com/chasr34/0d15e83bd759896f323e10ab9a2e9628

### Steps to Reproduce

1. start up minecraft launcher
2. launch game
3. thats it.

### What You Expected

Hopefully to load my custom personal modpack without issue (been busy fixing other little issues I've managed to figure out)

### What Happened Instead

When starting my game, the only thing I've been getting no matter what is "The Twilight Forest (twilightforest) encountered an error during the common_setup even phase"

### Additional Details

I do not use optifine with my personal modpack I've made, I have tried removing recent mods to my modpack with no success, yes I know I have other errors happening here and there due to it being such a large modpack, but not with this mod, I've tried using forge versions for 1.16.5 from 36.2.4 up to the most recent version (36.2.22), and no I have not had this issue prior with this mod.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment] 2021-12-21 00:18
Duplicate of #1420, downdate your Immersive Engineering

**Closed as completed by Drullkus** 2021-12-21 00:18 UTC
Labels: bug

**Comment by Drullkus** [comment] 2021-12-21 06:19
New Twilight Build on Curseforge will address the problem: https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/download/3575220
