### ISSUE TITLE
player exit when entering the server

### ISSUE THREAD

**Issue by MaikiOS** [TeamTwilight/twilightforest#566] opened 2018-06-28 07:22 UTC
Forge version: Minecraft Forge - MC 1.12.2 - 14.23.4.2705
Twilight Forest - MC 1.12.2 - 3.7.424
Link to crash log: https://gist.github.com/smert999/6a1cdba171266a0a70d809a18715068c

Steps to reproduce:
install SimpleDimensions-MC1.12-1.3.1, create an additional world with this mod and teleport to it, and there is a takeoff

I'm sorry for my English myself from Russia

**Comment by Andromander** [comment] 2018-06-28 07:26
This appears to be a duplicate of #334

**Comment by MaikiOS** [comment] 2018-06-28 07:48
the whole problem is solved by setting the patched mode

**Closed as completed** 2018-06-28 07:48 UTC
