### ISSUE TITLE
[Crash-reporter]

### ISSUE THREAD

**Issue by MokoBlack** [TeamTwilight/twilightforest#832] opened 2019-11-01 11:23 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  JechCore (JustEnoughCharacters-1.12.0-2.2.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CorePlugin (SmoothFont-1.12.2-1.12-b1.jar)
  ForgePlugin (CustomSkinLoader_Forge-14.7.jar)
  TabIconHackForgeLoadingPlugin (TabIconHackForge-1.0.jar)
  SmoothWaterCore (SmoothWater-0.1.4.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  iceandfire (iceandfire-1.8.2.jar)
  NetherPortalFixForgeLoadingPlugin (NetherPortalFixForge-1.0.jar)
  CoreModLoader (Sound-Physics-1.12.2.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/1/19 7:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at twilightforest.entity.boss.EntityTFNaga.findCirclePoint(EntityTFNaga.java:641)
	at twilightforest.entity.boss.EntityTFNaga.access$200(EntityTFNaga.java:54)
	at twilightforest.entity.boss.EntityTFNaga$AIMovementPattern.func_75246_d(EntityTFNaga.java:312)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at twilightforest.entity.boss.EntityTFNaga.func_70636_d(EntityTFNaga.java:396)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at twilightforest.entity.boss.EntityTFNaga.func_70071_h_(EntityTFNaga.java:486)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at twilightforest.entity.boss.EntityTFNaga.findCirclePoint(EntityTFNaga.java:641)
	at twilightforest.entity.boss.EntityTFNaga.access$200(EntityTFNaga.java:54)
	at twilightforest.entity.boss.EntityTFNaga$AIMovementPattern.func_75246_d(EntityTFNaga.java:312)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at twilightforest.entity.boss.EntityTFNaga.func_70636_d(EntityTFNaga.java:396)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at twilightforest.entity.boss.EntityTFNaga.func_70071_h_(EntityTFNaga.java:486)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: twilightforest:naga (twilightforest.entity.boss.EntityTFNaga)
	Entity ID: 543
	Entity Name: 娜迦
	Entity's Exact location: -248.17, 32.00, -250.64
	Entity's Block location: World: (-249,32,-251), Chunk: (at 7,2,5 in -16,-16; contains blocks -256,0,-256 to -241,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.02, -0.08, -0.12
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 新的世界
	All players: 1 total; [EntityPlayerMP['Moko_Black'/336, l='新的世界', x=-259.33, y=32.00, z=-243.21]]
	Chunk stats: ServerChunkCache: 221 Drop: 0
	Level seed: -7995815223216689254
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1896016824 bytes (1808 MB) / 3235905536 bytes (3086 MB) up to 3238002688 bytes (3088 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3088m
	IntCache: cache: 0, tcache: 2, allocated: 1, tallocated: 38
	FML: MCP 9.42 Powered by Forge 14.23.5.2813 Optifine OptiFine_1.12.2_HD_U_E3 60 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2813.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2813             | forge-1.12.2-14.23.5.2813.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jecharacters         | 1.12.0-2.2.2             | JustEnoughCharacters-1.12.0-2.2.2.jar         | None                                     |
	| LCHIJA | smoothfontcore       | 1.12.2-1.12              | minecraft.jar                                 | None                                     |
	| LCHIJA | smoothfont           | 1.12.2-1.12-b1           | SmoothFont-1.12.2-1.12-b1.jar                 | None                                     |
	| LCHIJA | applecore            | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                  | None                                     |
	| LCHIJA | jei                  | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| LCHIJA | betterwithmods       | 1.12-2.3.20-1037         | BetterWithMods-1.12-2.3.20-1037.jar           | None                                     |
	| LCHIJA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| LCHIJA | backstab             | 1.0.3.2                  | backstab-1.12.2-1.0.3.2.jar                   | None                                     |
	| LCHIJA | baubles              | 1.5.2                    | Baubles-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | betterwithaddons     | 0.50-hotfix2             | Better+With+Addons-0.50-hotfix2.jar           | None                                     |
	| LCHIJA | betteranimalsplus    | 7.1.1                    | betteranimalsplus-1.12.2-7.1.1.jar            | None                                     |
	| LCHIJA | bettercombatmod      | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LCHIJA | xaerobetterpvp       | 1.15                     | BetterPvP_1.15_Forge_1.12.jar                 | None                                     |
	| LCHIJA | bettertitlescreen    | 1.4b                     | BetterTitleScreen-1.12.2-1.4b.jar             | None                                     |
	| LCHIJA | betterwithlib        | ${version}               | BetterWithLib-1.12-1.5.jar                    | None                                     |
	| LCHIJA | chopdownupdated      | 1.12.2-1.2.4             | chopdownupdated-1.12.2-1.2.4.jar              | None                                     |
	| LCHIJA | codechickenlib       | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | combatrefined        | 1.4.1                    | combatrefined-1.4.1.jar                       | None                                     |
	| LCHIJA | customskinloader     | 14.7                     | CustomSkinLoader_Forge-14.7.jar               | None                                     |
	| LCHIJA | dungeontactics       | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar              | None                                     |
	| LCHIJA | fantasticlib         | 1.12.2.021               | FantasticLib-1.12.2.021.jar                   | None                                     |
	| LCHIJA | dynamicstealth       | 1.12.2.090               | DynamicStealth-1.12.2.090.jar                 | None                                     |
	| LCHIJA | gravestone           | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar            | None                                     |
	| LCHIJA | gravestone-extended  | 1.3.5                    | GraveStone-1.12.2-Extended-1.3.5.jar          | None                                     |
	| LCHIJA | grimoireofgaia       | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar            | None                                     |
	| LCHIJA | iblis_headshots      | 1.2.6                    | iblis-headshots-1.2.6 (1).jar                 | None                                     |
	| LCHIJA | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire           | 1.8.2                    | iceandfire-1.8.2.jar                          | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | jeresources          | 0.8.7.41                 | JustEnoughResources-1.12.2-0.8.7.41.jar       | None                                     |
	| LCHIJA | mobbattle            | 2.3.2                    | MobBattleMod-1.12.2-2.3.2.jar                 | None                                     |
	| LCHIJA | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| LCHIJA | nodami               | 1.2.1                    | nodami-1.12.2-1.2.1.jar                       | None                                     |
	| LCHIJA | parry                | 1.0                      | parry-1.0-hotfix (1).jar                      | None                                     |
	| LCHIJA | roughmobs            | 2.0.0                    | roughmobs2-1.12.2_2.0.13.jar                  | None                                     |
	| LCHIJA | smoothwater          | 0.1.4                    | SmoothWater-0.1.4.jar                         | None                                     |
	| LCHIJA | soundphysics         | 1.0.4                    | Sound-Physics-1.12.2.jar                      | None                                     |
	| LCHIJA | specialai            | 1.0.0_for_mc1.12.2       | specialai-1.0.1_for_mc1.12.2.jar              | None                                     |
	| LCHIJA | survivaltweaks       | 5.2.0                    | SurvivalTweaks-5.2.0-1.12.2.jar               | None                                     |
	| LCHIJA | texfix               | 4.0                      | TexFix+V-1.12-4.0.jar                         | None                                     |
	| LCHIJA | theoneprobe          | 1.4.20                   | theoneprobe-1.12-1.4.20.jar                   | None                                     |
	| LCHIJA | titlechanger         | 1.1.3                    | titlechanger-1.1.3.jar                        | None                                     |
	| LCHIJA | topaddons            | 1.12.2-1.4.0             | topaddons-1.12.2-1.4.0.jar                    | None                                     |
	| LCHIJA | twilightforest       | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHIJA | walljump             | 1.12.2-1.2.1             | walljump-1.12.2-1.2.1.jar                     | None                                     |
	| LCHIJA | warhammermod         | 1.9.2.5                  | warhammermod-1.9.2.5-(1.12.2).jar             | None                                     |
	| LCHIJA | waystones            | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LCHIJA | what                 | 0.2                      | WHAT-0.2.jar                                  | None                                     |
	| LCHIJA | wts                  | 1.1.0                    | WTS-1.1.0.jar                                 | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.1.95-mc1.12-alpha.jar         | None                                     |
	| LCHIJA | cyclopstek           | 1.0.34                   | cyclopstek-1.0.34.jar                         | None                                     |
	| LCHIJA | rtg                  | 6.1.0.0-snapshot.1       | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |
	| LCHIJA | primal_tech          | 0.3.5                    | PrimalTech-0.3.5.jar                          | None                                     |
	| UD     | netherportalfixforge | 1.0.0                    | minecraft.jar                                 | None                                     |
	| UD     | tabiconhackforge     | 1.0.0                    | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
JechCore (JustEnoughCharacters-1.12.0-2.2.2.jar)
  me.towdium.jecharacters.core.JechClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-1.12.2-1.12-b1.jar)
  bre.smoothfont.asm.Transformer
ForgePlugin (CustomSkinLoader_Forge-14.7.jar)
  customskinloader.forge.TransformerManager
TabIconHackForgeLoadingPlugin (TabIconHackForge-1.0.jar)
  kengxxiao.tabiconhack.coremod.TabIconHackForgeClassTransformer
SmoothWaterCore (SmoothWater-0.1.4.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
iceandfire (iceandfire-1.8.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
NetherPortalFixForgeLoadingPlugin (NetherPortalFixForge-1.0.jar)
  kengxxiao.netherportalfix.coremod.NetherPortalFixForgeClassTransformer
CoreModLoader (Sound-Physics-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  betterwithmods.library.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Moko_Black'/336, l='新的世界', x=-259.33, y=32.00, z=-243.21]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.66
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Andromander** [comment] 2019-11-01 11:26
Duplicate of #817

**Closed as completed** 2019-11-01 11:51 UTC
Labels: duplicate
