### ISSUE TITLE
(Suggestion) More structures

### ISSUE THREAD

**Issue by TheLastCookie11** [TeamTwilight/twilightforest#312] opened 2017-10-29 19:31 UTC
More ruins and structures to explore with maybe an new mob like undead...

**Comment by Tamaized** [comment] 2017-10-29 19:31
boi

**Comment by TheLastCookie11** [comment] 2017-10-29 19:31
yes ?

**Comment by Tamaized** [comment] 2017-10-29 19:31
stop spamming

**Comment by TheLastCookie11** [comment] 2017-10-29 19:31
ok srry

**Comment by Drullkus** [comment] 2017-10-29 19:31
Duplicate of #309 and #311 

Please stop posting duplicate issues please, thank you. If you continue I will report to Github

**Comment by TheLastCookie11** [comment] 2017-10-29 19:32
ok il stop

**Closed as completed by Drullkus** 2017-10-29 19:31 UTC
