### ISSUE TITLE
Mining Nether Gold Ore with a Fiery Pickaxe does not produce Gold Ingots

### ISSUE THREAD

**Issue by Untitled-1-dev** [TeamTwilight/twilightforest#1495] opened 2022-05-28 23:58 UTC
### Forge Version

40.1.19

### Twilight Forest Version

4.1.996

### Client Log

https://gist.github.com/Untitled-1-dev/db06aad09d811cd3bc6f8e8c367d7809

### Steps to Reproduce

1. Obtain a Fiery Pickaxe.
2. Mine Nether Gold Ore.

### What You Expected

Since smelting Nether Gold Ore gives you a Gold Ingot, you would expect the Fiery Pickaxe's Auto-Smelt feature to make Nether Gold Ore drop a Gold Ingot instead of Gold Nuggets.

### What Happened Instead

The Nether Gold Ore still drops Gold Nuggets.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2022-05-29 00:16
Autosmelt runs after other enchantments, so the way to make it drop a gold ingot is to add silk touch to the pick. Mining nether gold normally drops nuggets, and nuggets can't be smelted into ingots. Closing as this works as intended.

**Closed as completed** 2022-05-29 00:16 UTC
Labels: bug
