### ISSUE TITLE
Lack of CTM dependency doesn't crash.

### ISSUE THREAD

**Issue by purpleposeidon** [TeamTwilight/twilightforest#328] opened 2017-11-09 08:14 UTC

**Comment by Tamaized** [comment] 2017-11-09 08:16
Uhhh? Why would it crash?

**Comment by purpleposeidon** [comment] 2017-11-09 08:18
Well, I should say, ironwood blocks render mostly black, which is lame. So either it should crash or just render w/o CTM?

**Comment by Tamaized** [comment] 2017-11-09 08:20
Duplicate of #299

**Closed as completed by Tamaized** 2017-11-09 08:20 UTC
