### ISSUE TITLE
Minecraft Start up Error

### ISSUE THREAD

**Issue by LordSMRayquaza** [TeamTwilight/twilightforest#864] opened 2020-03-17 19:53 UTC
Forge version: 1.12.2-14.23.5.2847
Twilight Forest version: 1.12.2-3.10.1013
Link to crash log: https://paste.dimdev.org/cutucaqofu.mccrash
My Minecraft client provides me with this crash with the latest version of Twilight Forest. I'm also using the latest version of Forge for 1.12.2. I don't know what I am doing wrong.

**Comment by LordSMRayquaza** [comment] 2020-03-17 19:55
Plus, all I know is that it is an initializing error.

**Comment by Andromander** [comment] 2020-03-17 20:55
I believe this is an issue caused by Optifine, perhaps an outdated version?

**Comment by LordSMRayquaza** [comment] 2020-03-17 21:04
Then should I just remove Optifine, cause its not like I need it.

**Comment by bs2609** [comment] 2020-03-22 23:20
Duplicate of #686

**Closed as completed by bs2609** 2020-03-22 23:20 UTC
Labels: duplicate
