### ISSUE TITLE
Twilight Forest generating high up in sky, only structures generate and no terrain

### ISSUE THREAD

**Issue by SpencerMeow** [TeamTwilight/twilightforest#894] opened 2020-06-08 16:32 UTC
Forge version: 1.12.2
Twilight Forest version: 3.10.1013

Steps to reproduce:
1. Unknown

What I expected to happen:
Twilight forest generates normally
What happened instead:
Portal generates alone high up, no terrain generates, only structures.

https://user-images.githubusercontent.com/58450660/84056321-adca2880-a97b-11ea-9ca4-9b740f4dbb40.png

Any idea of a fix, or what mod might be causing it?

**Comment by Hugod000** [comment] 2020-06-08 16:33
there's a config option "skylight forest" where no land generates, only structures, check you don't have that enabled

**Comment by Tamaized** [comment] 2020-06-08 17:37
Yes this is the skylight forest terrain. Closing as working as intended unless it's found this is generating as so with the config option disabled. (Note, disabling after world generation wont change already generated chunks)

**Closed as completed by Tamaized** 2020-06-08 17:37 UTC
