### ISSUE TITLE
[Suggestion] x on the map

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1079] opened 2021-04-12 19:37 UTC
When you open the magic map and you have already killed a boss, an x ​​appears on the map above the boss to know that you have finished it :D

**Comment by Tamaized** [comment] 2021-04-12 20:36
This was suggested once before but as I said before it's not possible without major performance impact.

**Comment by Xetaxheb** [comment] 2021-04-14 23:59
hijack the way banners work? place one at the bottom or top of the world at boss death location?

**Comment by Tamaized** [comment] 2021-04-15 00:01
It's not that simple, banners arent structures.

**Comment by Andromander** [comment] 2021-05-26 09:46
Just noticed this is a duplicate of #701. It's quite similar in concept.

**Closed as completed by Andromander** 2021-05-26 09:46 UTC
Labels: suggestion
