### ISSUE TITLE
Client Crashed during forge initialization

### ISSUE THREAD

**Issue by DragonHalo99** [TeamTwilight/twilightforest#706] opened 2019-02-22 21:12 UTC
Forge version: 14.23.5.2808
Twilight Forest version: 3.9.851
Link to crash log: https://gist.github.com/DragonHalo99/b7bb1e32237b3b6bc4fc04cce5e6897a
Steps to reproduce:
1. 
Start Minecraft
What I expected to happen:
minecraft runs
What happened instead:
Crashed

**Comment by 3TUSK** [comment] 2019-02-22 21:13
Try remove JustEnoughID

**Comment by DragonHalo99** [comment] 2019-02-22 21:14
ok

**Comment by DragonHalo99** [comment] 2019-02-22 21:20
can't run the mod pack without justenoughid like i thought. I will switch back to the release version. I was mainly posting the crash log incase it would help with the dev build.

**Comment by Andromander** [comment] 2019-02-22 21:22
It's more to do with JEID trying to use Mixin on a method that doesn't exist here anymore. It is up to them to fix it.

**Comment by DragonHalo99** [comment] 2019-02-22 21:23
oh should I report that to JEID?

**Comment by Tamaized** [comment] 2019-02-22 21:24
duplicate of #685

**Closed as completed by Tamaized** 2019-02-22 21:24 UTC
Labels: duplicate
