### ISSUE TITLE
[1.18.2] Server Crash - Ticking Entity Crash

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#1682] opened 2022-11-07 04:31 UTC
### Forge Version

40.1.84

### Twilight Forest Version

 twilightforest-1.18.2-4.1.1423-universal.jar

### Crash Report (if applicable)

https://pastebin.com/LmtFgCnC

### Steps to Reproduce

Player inside Twilight Forest
Server Crashes

### What You Expected

Not to Crash

### What Happened Instead

crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment] 2022-11-08 00:13
There's more to this crash than just "player was inside TF and then it crashed". The cause of this crash would only happen if something was shot at by a Slime Beetle as the projectile is the cause.

I can look into a potential fix, though this would only be for the 1.19 version.

Edit: been digging around but I'm not sure of a reliable way to reproduce this. What equipment were you wearing at the time?

**Comment by MokahTGS** [comment] 2022-11-08 15:41
I'm sure there is more to it, but that was the information I had, since it wasn't me experiencing the crash.  I'm admin on a server that is having this issue and the players are experiencing it.  I'll try to get info from the player, but since they can't get back on the server since the crash it might prove difficult.  It also sounds moot, since you aren't going to fix it for 1.18.2...this isn't a 1.19 server.

This is on the Cosmic Magitech modpack so if there is a mod incompatibility I can get you the mod list.

https://www.curseforge.com/minecraft/modpacks/cosmic-magitech

Here's the modlist: https://pastebin.com/2aK004x4

**Comment by Tamaized** [comment] 2023-02-06 19:21
Fixed in 9b508acd581ca9ad00231e186add16dc34e527e1

**Closed as completed by Tamaized** 2023-02-06 19:21 UTC
Labels: bug
