### ISSUE TITLE
No hostile mobs spawning in TF

### ISSUE THREAD

**Issue by genthug** [TeamTwilight/twilightforest#634] opened 2018-09-30 02:37 UTC
Forge version: 
Twilight Forest version: 14.23.4.2755
Link to crash log: Do not have crash log as the game did not crash

Steps to reproduce:
1. Download Roguelike Adventures and Dungeons modpack
2. Go into Twilight Forest
3. Notice that no aggressive mobs are spawning above ground

What I expected to happen:
Aggressive mobs to spawn above ground without the need of spawners.
What happened instead:
The only aggressive mobs that I see spawn are either underground or the bosses themselves, or are from spawners. No other hostile mobs spawn above ground by themselves.

**Comment by Andromander** [comment] 2018-10-01 01:31
I'm uncertain if this is affecting other mod's mobs from spawning, however, there is intended behaviour in this. 

Alone, Twilight Forest attempts to not spawn hostile mobs on the surface, only underground, in structures, or with the assistance of spawners. The only exceptions are Mosquito Swarms, Mist Wolves, King Spiders, Yeti, and Winter Wolves, but only in select biomes. Other mods can spawn hostile mobs on the surface, but I'm uncertain if this modpack adds any mods that would do this.

If the Swamp, Dark Forest, and Snowy Forest are not spawning their hostile mobs (listed above), then there might be an issue, or intended behaviour by the modpack.

**Comment by Andromander** [comment] 2021-05-25 10:57
Closing as monsters spawning on the surface are not similar to the ones that may spawn underground. If the pack is supposed to add more spawns, it would be best to report it to the pack.

**Closed as completed by Andromander** 2021-05-25 10:57 UTC
