### ISSUE TITLE
twilightforest is crashing (doesn't let minecraft open)

### ISSUE THREAD

**Issue by TainanRezende** [TeamTwilight/twilightforest#1421] opened 2021-12-21 00:14 UTC
### Forge Version

36.2.22

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/TainanRezende/9bb5f5b2fb6bf5ce6f5a998fc09ac18b

### Crash Report (if applicable)

https://gist.github.com/TainanRezende/ef8b88d9da376fc1ccf3710597f56f16

### Steps to Reproduce

this error starts after I updated immersive engineering in my mods pack that I created, version of immersive engineering: ImmersiveEngineering-1.16.5-5.0.6-141, then after updating the version I start to give this problem, in the version before this does not happen that.

### What You Expected

the game has opened normally

### What Happened Instead

the game doesn't open because of this

### Additional Details

I know the solution could be just not updating but my modpack is based on these two mods (not only them but I can understand) so I was wondering if it's a Twilight issue or if I should report it or ImmersiveEngineering.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Jordan231111** [comment] 2021-12-21 00:24
Have exactly the same issue

**Comment by Drullkus** [comment] 2021-12-21 00:25
Duplicate of #1420, downgrade your IE

**Closed as completed by Drullkus** 2021-12-21 00:25 UTC
Labels: bug

**Comment by GizmoTheMoonPig** [comment] 2021-12-21 00:36
Please DO NOT report this to them. It's not their fault they decided to change something that we use. I will push a fix as soon as I can.

**Comment by Jordan231111** [comment] 2021-12-21 00:39
Ok thanks!
