### ISSUE TITLE
Hydra heads de rendered when died on relogged are completely gone.

### ISSUE THREAD

**Issue by zmastervader** [TeamTwilight/twilightforest#518] opened 2018-05-23 06:07 UTC
Forge version: 14-23.3.2679
Twilight Forest version: 3.6.345

Steps to reproduce:
1. Died to the Hydra in SevTech 3.0.7, when I ran back Hydra heads were gone but shooting fire.
2. I logged out and when I logged back in only the Hydra body was left.

What I expected to happen: Hydra heads to respawn due to rendering bug on my end.

What happened instead: Hydra body is invincible.

**Comment by Seth0067** [comment] 2018-09-09 00:05
I just had this happen to me as well.  I don't suppose having the save world might be helpful would it?  Reproduction as you say is what you probably need to fix, but if they save helps I can stick it on dropbox for you to look at.

**Comment by Andromander** [comment] 2018-09-09 01:28
Attempted to reproduce this with TF 3.8.677, Forge 14.23.4.2759, and the available mods in the pack Do I am Cake? However, I cannot reproduce this.

The following were tested, all with a Hydra spawned:
* Teleport and Re-entered the Twilight Forest
* Died to the Hydra
* Quit and Re-entered the world in range of the Hydra
* Quit and Re-entered the world in the Overworld, then teleport back onto the Twilight Forest
* Flew out of range of the Hydra (chunks unloaded, no boss bar), quit and re-entered, then flew back)

It may have been fixed either in 3.8.654, any of the dev versions afterwards, fixed with a different Forge version, or there is something that SevTech does that causes this error to occur (either it be a mechanic change or a mod that exists in the pack).

**Comment by Tamaized** [comment] 2019-05-09 23:12
Does this still happen on the latest builds?

**Comment by jddorton** [comment] 2019-07-19 21:19
Had this happen to me just now on SevTech Ages 3.1.1 that runs twilightforest-1.12.2-3.8.689-universal.jar. Reproduced with the same steps the original poster mentioned. Ended up just using the /kill command to kill him and collect his loot.

**Comment by GizmoTheMoonPig** [comment] 2021-10-18 03:08
this shouldnt be an issue anymore thanks to the new multipart system. If you encounter something like this again in a more modern version (1.16 and above WITHOUT optifine) please report it

**Closed as completed by GizmoTheMoonPig** 2021-10-18 03:08 UTC
