### ISSUE TITLE
Missing textures on items

### ISSUE THREAD

**Issue by Hexarr** [TeamTwilight/twilightforest#1118] opened 2021-05-05 08:49 UTC
Forge version: forge-1.16.5-36.1.0
Twilight Forest version: twilightforest-1.16.5-4.0.435-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
It doesnt crash
Steps to reproduce:
1.Go in creative
2.Find These items :
Keepsake Casket 
Twilight oak door
Canopy door
Mangrove door
Darkwood door
Timewood door
Transwood door
Minewood door
Sortingwood door
3.  All of the items listed above have missing textures

[missing textures](https://user-images.githubusercontent.com/68790281/117116834-20f83c80-ad8f-11eb-840e-b4743dc81381.png)

What I expected to happen:
For items to have textures
What happened instead:
The items didnt have textures

**Comment by TheOnlyMann** [comment] 2021-05-05 08:54
currently they dont have item textures, as they will get a new one. wait out for now.

**Comment by GizmoTheMoonPig** [comment] 2021-05-05 15:04
duplicate of #1035

**Closed as completed by GizmoTheMoonPig** 2021-05-05 15:04 UTC
