### ISSUE TITLE
twilightforest-common.toml is not correct. Correcting

### ISSUE THREAD

**Issue by Trackhe** [TeamTwilight/twilightforest#1129] opened 2021-05-17 14:48 UTC
Forge version: 36.1.16
Twilight Forest version: twilightforest-1.16.5-4.0.435-universal.jar
log: `server/config/twilightforest-common.toml is not correct. Correcting`

Steps to reproduce:
1.  Use twilightforest-1.16.5-4.0.435-universal.jar and forge. start the client or the server and show your logs.

What I expected to happen:
A correct config.

What happened instead:
They say that he correct the config because he is not correct but nothing happend. and i diddnt change something at the config. this is the default config.

**Comment by GizmoTheMoonPig** [comment] 2021-05-17 14:50
duplicate of #1073

**Closed as completed by GizmoTheMoonPig** 2021-05-17 14:50 UTC

**Comment by Trackhe** [comment] 2021-05-17 14:56
@GizmoTheMoonPig to what extent is this a duplicate?

**Comment by GizmoTheMoonPig** [comment] 2021-05-17 14:57
config option is currently broken for everyone, and shows the error whether you change it or not. We'll look into it

**Comment by Trackhe** [comment] 2021-05-17 14:59
i looked in to it but the log that he provided is completly different. but okey thanks.

**Comment by GizmoTheMoonPig** [comment] 2021-05-17 15:55
regardless, its fixed now and will be in the next beta
