### ISSUE TITLE
1.12.2 Parsing error loading built-in advancement twilightforest:alt/compat/tc_aspects

### ISSUE THREAD

**Issue by Caaruzo** [TeamTwilight/twilightforest#804] opened 2019-08-16 22:33 UTC
Greetings,

when the Forge server is booting up i receive this error without any crash, just to let you know for fix.

```
[Server thread/ERROR] [FML]: Parsing error loading built-in advancement twilightforest:alt/compat/tc_aspects
com.google.gson.JsonSyntaxException: Unknown item id 'thaumcraft:thaumonomicon'
	at net.minecraft.advancements.critereon.ItemPredicate.func_192492_a(ItemPredicate.java:127) ~[an.class:?]
	at net.minecraft.advancements.critereon.ItemPredicate.func_192494_b(ItemPredicate.java:163) ~[an.class:?]
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192166_a(SourceFile:62) ~[al.class:?]
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192166_a(SourceFile:21) ~[al.class:?]
	at net.minecraft.advancements.Criterion.func_192145_a(SourceFile:35) ~[n.class:?]
	at net.minecraft.advancements.Criterion.func_192144_b(SourceFile:46) ~[n.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:204) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1369) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1351) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1325) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Forge Version:** forge-1.12.2-14.23.5.2838-universal
**Minecraft Version:** 1.12.2
**Using Sponge?** No
**Twilight Forest Version:** twilightforest-1.12.2-3.9.984-universal

**Comment by bs2609** [comment] 2019-08-16 22:36
Duplicate of #753

**Closed as completed by bs2609** 2019-08-16 22:36 UTC
Labels: duplicate
