### ISSUE TITLE
OVERSPAWNING of bosses. 300 every 5 seconds

### ISSUE THREAD

**Issue by davizon200** [TeamTwilight/twilightforest#866] opened 2020-03-22 22:56 UTC
So spawner (like for example naga spawner) breaks, but it keeps spawning a crazy amount of naga's that is unbearable and creates some horrible lag if you are close... we tried in different naga dungeons and the skeleton mage dungeon as well and same thing...

We are playing in a multiplayer server using MCProhosting in a biomes O'Plenty seed...

I have tried deleting the dimension to restart the map and still happens... (Curiously dimension is 777 and not 7)...

I have also tried with the same mods in singleplayer and it functions as expected, 1 naga appears and spawner breaks and THAT'S IT.

I need some SERIOUS help to fix this for my online server... profesionals, PLEASE HELP! even the staff at MCProhosting can't do shit with this...

Forge version: 1.12.2-14.23.5.2768
Twilight Forest version: 1.12.2-3.8.689
Link to crash log: no crash unless i stay where bosses keep spawning.

Steps to reproduce:
1. Go to Naga stage (for example)
2. Once inside crazy overspawning of bosses spawning. (around 300 every 5 seconds)

What I expected to happen:
1 Boss to spawn.

What happened instead:
infinite bosses spawn.

Sincerely,

Alfkors / davizon200

**Comment by Tamaized** [comment] 2020-03-22 23:00
Sounds more like some server side mod or plugin is preventing the spawner from being removed for whatever reason.

**Comment by davizon200** [comment] 2020-03-22 23:14
so no chance anyone here can help then huh... :(

**Comment by Drullkus** [comment] 2020-03-22 23:16
Sounds like you have a protection plugin acting rogue and circumventing our spawn-only-once measure

**Comment by davizon200** [comment] 2020-03-22 23:20
okay that sounds promising, could you guys help me detect which it is? im using Sponge forge in MCProhosting server, thats the only difference i can think of from singleplayer working, other than single player not being in Biomes O' Plenty seed and server is...

**Comment by Drullkus** [comment] 2020-03-22 23:21
Check sponge configs and see if they’re disallowing entities from breaking blocks

Try turning off the mob griefing gamerule and see if that fixes it too

**Comment by davizon200** [comment] 2020-03-22 23:23
okay i will check... i will let you know once i do so, i will speak with someone from MCProhosting as well to help me with these tests...

**Comment by bs2609** [comment] 2020-03-22 23:24
Probably a duplicate of #739, see also the Sponge issue linked there (https://github.com/SpongePowered/SpongeForge/issues/2682).

If that's the case, you'll need to update.

**Comment by davizon200** [comment] 2020-03-22 23:28
HI @bs2609 THAT IS EXACTLY WHAT HAPPENS! Is the solution anywhere? is this it?: "Confirmed fixed in spongeforge-1.12.2-2768-7.1.6-RC3651.jar."

**Comment by davizon200** [comment] 2020-03-22 23:45
can someone link me that version of spongefoirge? i cant seem to find it here...: https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2?until=2019-04-20T01%3A33%3A28Z

**Comment by davizon200** [comment] 2020-03-22 23:59
OKAY FIXED!
1.12.2-2768-7.1.6-RC3657 SpongeForge version works as well...
thank you for your awesome replies everyone! I LOVE YOU ALL!
Sincerely,
Alfkors / davizon200

**Closed as completed** 2020-03-23 00:06 UTC
Labels: duplicate
