### ISSUE TITLE
robust twilight trees glitch

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1252] opened 2021-08-29 11:14 UTC
Forge version: whatever version the modpack is on.
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. load up the seed given in the screenshot. then go to the coordinates provided, then look for yourself.

What I expected to happen: when i found the robust twilight trees, i expected them to be loaded properly.

What happened instead: not only was the ores outside of the hollow hill, but the robust twilight trees had parts of them that were cut off by the structure boarder. this will be carried over into another ticket
![2021-08-29_06 06 40](https://user-images.githubusercontent.com/68449401/131248416-1f486a0d-0e25-4f5d-8302-83a2c1fe1137.png)
![2021-08-29_06 06 48](https://user-images.githubusercontent.com/68449401/131248417-37dff784-f1e0-4623-8882-6ce9a356a30f.png)

**Comment by Andromander** [comment] 2021-08-29 12:41
Duplicate of #1047

**Closed as completed by Andromander** 2021-08-29 12:41 UTC
Labels: duplicate
