### ISSUE TITLE
Baubles always retained after death without charm of keeping

### ISSUE THREAD

**Issue by bmwalter68** [TeamTwilight/twilightforest#574] opened 2018-07-09 18:01 UTC
Forge version: 14.23.4.2705
Twilight Forest version: 1.12.2-3.7.424
Link to crash log: not a crash

Steps to reproduce:

1. Install mods: Baubles (1.5.2) Twilight Forest (3.7.424) JEI (4.11.0.202, optional)
2. Create survival world with cheats on
3. Obtain Miners ring via JEI or /give and equip in ring slot
4. Switch to creative mode and fly to a great height
5. Switch to survival mode and fall to your death

What I expected to happen:

Bauble (Miners Ring) will be dropped along with any other inventory contents.

What happened instead:

Bauble (Miners Ring) is still equipped in ring slot.  This happens with any bauble, I initially noticed it with Silent's Gems Chaos Gem.

As a side note, this has an interaction with GraveStone Mod (1.10.1) in my pack.  I noticed this issue because on death all player baubles are disappearing permanently.  I am still trying to nail down why they disappear, but wanted to post this super-simplified example first since it is the root cause of that issue. (Baubles don't make it to inventory drops because they are getting intercepted by TF and thus don't wind up with the gravestone loot)

**Comment by Hubry** [comment] 2018-07-09 18:05
Duplicate of #542, should be fixed by b4dca0b6ed75f708c20a1d558594e84afcb4d5ad.

**Comment by bs2609** [comment] 2018-07-09 18:08
Heh, seems I was beaten to it.

That issue should be fixed, but let us know if you find a different issue.

**Closed as completed by bs2609** 2018-07-09 18:08 UTC

**Comment by bmwalter68** [comment] 2018-07-09 18:28
Actually, I have a follow-up.  I confirmed in my pack that baubles disappear in server play, but not in single player mode.  Apparently the baubles are not being put back into the inventory on server respawn.  I imagine it would affect server-based players who actually have the charm of keeping as their baubles would be deleted rather than repopulated in that case.

Is it possible to disable the charm of keeping?

I will research this a little more and try to come up with a simple repeatable example.  When I do I'll open a new issue.

**Comment by bs2609** [comment] 2018-07-09 21:04
I did some testing using a seperate server instance, and this seems to be ok in dev - either baubles are dropped on the ground if you don't have a charm, or they appear to be restored correctly to the bauble inventory.

If you can come up with a good test, I will check that as well. If you would like to test the current development builds yourself, you can get them [here](http://builds.steamnsteel.info/browse/TF-ONETWELVE/latest/artifact) (the "universal" artifact on that page).

**Comment by bmwalter68** [comment] 2018-07-09 21:12
I just updated my pack to use build 507 and can confirm that baubles are correctly not being saved without the charm of keeping.  There is, however, still some kind of conflict with the GraveStone Mod and possibly others.  First observations:

1) Death with no charm of keeping, all is as expected.  All gear in the gravestone.
2) Death with charm of keeping level 3, my baubles are equipped after respawn (except the charm of keeping) and none of my normal inventory is in the gravestone.  The inverse of my initial observation where my baubles disappeard and my normal inventory was preserved.

I will try to come up with a simplified example to show this and post a new issue more descriptive of what I'm seeing since this issue seems resolved since build 462.

**Comment by Tamaized** [comment] 2018-07-09 21:19
~The latest dev build is 559, not 507. See the link posted above.~
Sorry I somehow read that as "not correctly" my mistake :stuck_out_tongue:
