### ISSUE TITLE
Add support for 1.19

### ISSUE THREAD

**Issue by SussyAmgogus** [TeamTwilight/twilightforest#1598] opened 2022-08-09 20:47 UTC
### The Suggestion

Add it because honestly I am losing my shit, the mod finally updated and this is the only one not supporting JavaFML 41.

### Why Should It Be in the Mod?

If you've added 1.19.2 and 1.19.1, why make it needlessly infuriating for those who are on 1.19 and don't want to update?

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment] 2022-08-09 20:49
Duplicate of #1596

**Closed as completed by jodlodi** 2022-08-09 20:49 UTC
Labels: suggestion

**Comment by Tamaized** [comment] 2022-08-09 20:53
Nah
