### ISSUE TITLE
The Light Problem In Minecraft 1.16.5

### ISSUE THREAD

**Issue by JaggedMarker9264** [TeamTwilight/twilightforest#1713] opened 2022-12-27 08:58 UTC
### Forge Version

36.2.39

### Twilight Forest Version

4.0.412

### Steps to Reproduce

1. Open Minecraft client (With Optifine, Forge, Appleskin, JEI and The Legend Of Herobrine )
2. During the opening process, "Worlds using Experimental Settings are not supported" will be displayed, and click "I know what I am doing!"
3. After entering the world and entering the Twilight Forest, you will see some black squares (including grass)and destroy some things (such as mushrooms and grass), the black will turn to other squares.At the same time, the message "OpenGL Error: 1281 (Invalid value) appears

### What You Expected

The ground is intact without black squares and not appear"OpenGL Error".

### What Happened Instead

Entering the world and entering the Twilight Forest will see some black squares (including grass)and destroy some things (such as mushrooms and grass), the black will turn to other squares.The message "OpenGL Error: 1281 (Invalid value) appears

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment] 2022-12-27 09:56
> I have confirmed this bug can be replicated without the use of Optifine.

Let me get this straight: you encountered an issue where the game has Optifine installed, created this issue as such, and checked this specific checkbox that explicitly states this issue can be reproduced without Optifine. The *first* checkbox requires you do not have Optifine installed because any bugs that arise as a result of it cannot be fixed by us as it is difficult if not impossible for us to know what they are doing.
If you did initially have this unchecked and only checked it because the issue could not be submitted without it, perhaps there's a good reason why that is the case.

Unless you can reproduce this issue without Optifine, this issue is invalid.

**Closed as completed by Andromander** 2022-12-27 09:56 UTC
Labels: optifine
