### ISSUE TITLE
Anti-Builders destroy Iron Chest Shulker Boxes

### ISSUE THREAD

**Issue by szavak** [TeamTwilight/twilightforest#838] opened 2019-11-25 23:14 UTC
Forge version: 14.28.5.2847
Twilight Forest version: 3.10.1013
Link to crash log: Not a crash

Steps to reproduce:
1.  Put any amount of items in any variety of Iron Chests mod's larger shulker boxes
2. Place it near an anti builder

What I expected to happen: It to break the block and drop it as an item, like it does with regular shulker boxes

What happened instead: It completely destroyed the block, contents included

**Comment by bs2609** [comment] 2019-11-26 06:50
Duplicate of #659

**Closed as completed by bs2609** 2019-11-26 06:50 UTC
Labels: duplicate
