### ISSUE TITLE
Server crashes upon approaching castle like structure with thorns surrounding it

### ISSUE THREAD

**Issue by Justin16thomas** [TeamTwilight/twilightforest#1712] opened 2022-12-26 20:12 UTC
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1468

### Client Log

https://mclo.gs/YfO6nCt

### Crash Report (if applicable)

https://mclo.gs/YfO6nCt

### Steps to Reproduce

1. Approach castle like structure surrounded by thorns in multiplayer alone or with a friend
2. Wait about 1-2 minutes
3. Crash. Server will no longer allow anyone to join the server until you restart it. Issue is consistently reproducible 

https://imgur.com/QVNUiLD 
This is a link to the structure I'm referring to. Do not know the name of it since I'm new to the mod

### What You Expected

I expected to be able to explore the castle like structure with thorns without issue

### What Happened Instead

The game crashed.

### Additional Details

No other mods are installed. Twilight Forest is the only mod installed and running on the server and the client. It appears the issue is sorely in regards to the twilight mod itself, not conflicting mod packs.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment] 2022-12-27 10:01
Looks like a duplicate of #1699

**Closed as completed by Andromander** 2022-12-27 10:01 UTC
Labels: bug
