### ISSUE TITLE
Naga boss bar in overworld 

### ISSUE THREAD

**Issue by disastercube** [TeamTwilight/twilightforest#968] opened 2020-10-04 16:05 UTC
**Minecraft 1.12.2**
----------------------------------------------------------
For some reason I **rarely** find **Naga's** boss bar while in the overworld. The bar is not always there, but you find it while exploring/loading new chunks. When found, it won't go away even after reloading, instead you'll have to move further (as for when you move further from the boss, the boss bar disappears). I thought it might have been a bug with my world, but after founding it again in another world, it seems a little bit strange.

- I tried checking underground in spectator to see if the boss spawned there, but so far haven't found nothing.

![2020-10-04_17 55 16](https://user-images.githubusercontent.com/62697421/95020542-1f855b00-066c-11eb-87e8-3fdd7e4e1d08.png)

**Comment by Tamaized** [comment] 2020-10-04 18:10
Could this be the same as #913 ?

**Comment by SurpriseAssassin** [comment] 2020-10-18 21:29
Your only seeing the health bars, currently playing the latest version of R.A.D and while i had around 3 nagas that appeared at my house, that I killed, I have had an unknown amount of them being invisibile and just destroying the blocks below and around me... Both underground and in the sky. All at my house.

**Comment by Gunner76th** [comment] 2020-11-03 23:55
This is 100% the same issue as #913 The mod team is aware of and is working on resolving this issue. Naga for some reason are spawning in Stone Beach Biomes. Please follow #913 for any updates, and I would suggest closing this as it is a duplicate of my posted issue.

**Comment by Gunner76th** [comment] 2020-11-03 23:56
Also, you are seeing the health bar because the Naga is within 2-6 chunks of you.

**Comment by disastercube** [comment] 2020-11-04 15:13
I'm fully aware of the way bosses name tags work and this issue was already solved in the latest OTG mod .

**Comment by Gunner76th** [comment] 2020-11-05 01:25
> I'm fully aware of the way bosses name tags work and this issue was already solved in the latest OTG mod .

Latest being what version of the mod and in Dev or actual release channel on Curse? Please refrain from saying "latest OTG mod" as there is Dev channel which you can get from their Discord, and stable channel which is on Curseforge. 
Also as I stated, your duplicate issue is 100% a duplicate of my original issue #913 which means yours should be closed and marked as duplicate. 

If you are stating that OTG 9 that is released on Curseforge has resolved the issue of Naga in Stone Beach biomes, can you please provide the documentation and commit link for this? I have seen nothing so far on the changelog stream.

**Comment by disastercube** [comment] 2020-11-05 14:57
The latest version in dev but released on the OTG discord server (1.12.2_-_v9.0_r10 and up I think).
PG85/OpenTerrainGenerator@044e3e4

**Closed as completed** 2021-01-22 17:04 UTC
Labels: other mod
