### ISSUE TITLE
Game crash on start up with Immersive Engineering installed

### ISSUE THREAD

**Issue by logixcraft** [TeamTwilight/twilightforest#1509] opened 2022-06-03 11:49 UTC
### Forge Version

40.1.25

### Twilight Forest Version

4.1.1052-universal

### Crash Report (if applicable)

https://gist.github.com/logixcraft/27b52ffa9f4006017be7cca868776822

### Steps to Reproduce

Added to a modified version of ATM7

### What You Expected

Game start up

### What Happened Instead

Failure message: Immersive Engineering (immersiveengineering) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5

### Additional Details

Game loads fine without Twilight Forest

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment] 2022-06-03 11:53
Duplicate of #1499.

**Closed as completed by Andromander** 2022-06-03 11:53 UTC
Labels: bug, duplicate
