### ISSUE TITLE
Hydra, Winter Wolf and Fire Beetle's breath do no damage.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#238] opened 2017-10-15 04:52 UTC
Forge version: 2501
Twilight Forest version: 3.1.139
Link to crash log: Not a crash
Steps to reproduce:
1. Fighting against them.

What I expected to happen:Their breath does damage.

What happened instead:but they don't.

**Comment by Tamaized** [comment] 2017-10-15 04:53
#229

**Comment by Tamaized** [comment] 2017-10-19 05:23
Gonna close this one since it's a dupe of the other

**Closed as completed by Tamaized** 2017-10-19 05:23 UTC
