### ISSUE TITLE
[1.18.2]  Twilight Forest lacks proper skybox, breaking certain shaders

### ISSUE THREAD

**Issue by Reshy** [TeamTwilight/twilightforest#1614] opened 2022-08-28 14:02 UTC
### Forge Version

40.1.73

### Twilight Forest Version

 twilightforest-1.18.2-4.1.1397-universal.jar

### Steps to Reproduce

1.  Use a shader like Makeup Ultrafast
2. Enter Twilight Forest

### What You Expected

The sky shouldn't suffer from weird graphical smearing on the bottom half of the sky when using shaderpacks.

### What Happened Instead

![2022-08-28_07 00 09](https://user-images.githubusercontent.com/2096384/187077689-aaf2f074-c9e5-4e56-b5a0-73a46b3ffdd4.png)
![2022-08-28_07 01 39](https://user-images.githubusercontent.com/2096384/187077736-f816fb74-2656-4404-8991-95fe51360715.png)
![2022-08-28_07 01 42](https://user-images.githubusercontent.com/2096384/187077749-02ca5e7d-05b7-4b88-af7e-9799b56a1a6a.png)
![2022-08-28_07 01 59](https://user-images.githubusercontent.com/2096384/187077791-e0da82db-ae16-4565-8fe2-4a75cd2fb8d2.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2022-08-28 14:08
duplicate of #854, #1046, AND #1501. Its already been stated we cant fix this issue. Try using a different shaderpack, some of them dont break our skybox

**Closed as not planned by GizmoTheMoonPig** 2022-08-28 14:08 UTC
Labels: duplicate, wontfix, shut
