### ISSUE TITLE
Crash when fighting Hydra

### ISSUE THREAD

**Issue by Neglevin** [TeamTwilight/twilightforest#613] opened 2018-09-02 16:31 UTC
Forge version: 14.23.2759
Twilight Forest version: 3.8.564
Link to crash log: https://paste.dimdev.org/ucufenirac.mccrash

Steps to reproduce:
1. Go into the dimension
2. Try to cut off the Hydra's head and fight it

What I expected to happen:
I expected to be able to kill the Hydra without crashing.

What happened instead:
I crashed when I was trying to fight it.

**Comment by Andromander** [comment] 2018-09-03 04:56
Unable to reproduce with the modpack `Do I am Cake?`. You might be clashing with another mod that's adding something to the Hydra Head entity, but I'll have to look into what might even be causing this.

**Comment by bs2609** [comment] 2018-09-03 06:10
Might be fixed by 88556269077ee994774e796a335ac968c0d7ac78, though it's hard to be sure without a reproduction.

**Comment by bs2609** [comment] 2018-09-22 10:14
Closing this as 3.8.689 has been released on CurseForge. It can be reopened if people run into the same crash in that version, otherwise it can be considered fixed.

**Closed as completed by bs2609** 2018-09-22 10:14 UTC
Labels: bug
