### ISSUE TITLE
Attempting to add TF to a modpack

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#873] opened 2020-04-13 20:44 UTC
Forge version: MC 1.12.2 14.23.5.2838
Twilight Forest version: (this is the build number)
Link to crash log: https://paste.dimdev.org/depecaxiso.mccrash
Steps to reproduce:
1. Download classic pack 3.1.6
2.Use Classic pack Crate (a various set of extra mods and reworks including Aether_ii, CTM, Chisel, twilight forest latest version, Patchouli, Biomes O plenty and Latest sponge RC4011 with forge 2838 replacing the prior)
3. load the new Classic pack from technic.
What I expected to happen:
Load into modpack with added mods
What happened instead:
Modpack failed on initialization
![Crash](https://user-images.githubusercontent.com/33814468/79159313-b132a080-7d8c-11ea-8225-d554667f5216.JPG)

**Comment by bs2609** [comment] 2020-04-13 20:46
Duplicate of #685

**Closed as completed by bs2609** 2020-04-13 20:46 UTC
Labels: duplicate
