### ISSUE TITLE
[1.12.2] on the Sponge server to brush out Hydra Duskwood but not he did not hit me

### ISSUE THREAD

**Issue by DownPower** [TeamTwilight/twilightforest#445] opened 2018-03-12 12:08 UTC
Forge version: forge-1.12.2-14.23.2.2611-universal
Twilight Forest version:Twilight Forest - MC 1.12.2 - 3.6.345
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:Natural Hydra will be killing the game player

What happened instead:But he wouldn't hit me if he couldn't get it
Feedback from Chinese players

English may not be very good
Hydra motionless, a generation is static in the creation mode
The following is my module：
FastLeafDecay—叶子快速腐烂
InventoryTweaks——R键整理
Iron Chests 更多箱子
Just Enough Items——JEI物品管理器
JourneyMap——旅行地图
Mob Grinding Utils-刷怪塔实用设备
[Neat——简洁的血条
OptiFine——高清修复
[-SimpleOres]一个神奇的矿石MOD 
SlashBlade——拔刀剑
TheTwilightForest——暮色森林
VeinMiner——矿脉矿工
Waila Harvestability-Waila的更多信息矿物显示辅助
IC2_experimental-工业2实验版
TinkersConstruct——匠魂
Chinjufu——镇守府
Forestry——林业
MrCrayfish's Furniture - 家具
Yarr Cute Mob Models 怪物娘化
Applied Energistics 2——应用能源2                
NotEnoughItems] NEI 内置合成表
CustomSkinLoader——万用皮肤补丁+正版可正常显示
The Heartwork——心血结晶，拔刀剑拓展
BuildCraft建筑
[Iron Tanks----铁储罐]
Botania---植物魔法
水晶花园——植物魔法的空岛模式 植物魔法拓展
Environmental Tech-环境技术
Wearable Backpacks——科学背包 
The right display is Chinese, please ignore
![jztu km ebm m km411g ah](https://user-images.githubusercontent.com/37296078/37282923-0a51f054-2631-11e8-84ef-6cd7fe988615.jpg)
This situation exists only in the Sponge server and does not exist in a single person mode.

**Comment by Drullkus** [comment] 2018-05-09 21:44
Duplicate of #313 

Open `config/sponge/global.conf` and set the `max-bounding-box-size` to `6000` or higher, or `0`.

Sponge's default maximum bounding box is too low for the Hydra.

**Closed as completed by Drullkus** 2018-05-09 21:44 UTC
