### ISSUE TITLE
"Currently Unknow Dimension Type!" using Xaero Map Mod

### ISSUE THREAD

**Issue by itsdaffxter** [TeamTwilight/twilightforest#1940] opened 2023-12-05 04:53 UTC
### Forge Version

47.2.6

### Twilight Forest Version

4.3.1893

### Steps to Reproduce

1. Went to Twilight Forest 
2. Minimap not loaded because "Currently Unknow Dimension Type!"
3. Re-enter problem persists
![Screenshot_twf](https://github.com/TeamTwilight/twilightforest/assets/105346673/37eed8e4-562c-4785-9e73-22081fa16bd1)

### What You Expected

Run normally as before modpack update "Better MC 4 v23"

### What Happened Instead

Xaero map, Twilight Forest conflicts? minimap not showing on Xaero especially Twilight Forest World

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment] 2023-12-05 04:57
I would argue this is on their end, we use vanilla's system for dimension types.

**Comment by AriaElidove** [comment] 2023-12-05 04:59
I can confirm this. Minimap v23.8.4 and WorldMap v1.36.0 both work with Twilight Forest, so I would recommend to backport to those versions for now until Xaero releases a fix.

**Comment by AriaElidove** [comment] 2023-12-05 05:19
So it looks like it's a new feature Xaero added into the World Map that's breaking Twilight Forest (Or visa versa). There seems to be a new feature that they added where you can toggle between dimensions on the map (via keybind or funny button at the top there)
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/184231e9-1f7e-407a-829f-58c87602202b)

I have no clue why Xaero's World Map is breaking to register Twilight Forest as a dimension, but it was completely fine in v1.36.0

Xaero's Minimap doesn't have this issue though from what I saw, so you can update it as youd like.

**Comment by Tamaized** [comment] 2023-12-05 05:21
Report it to them please.

**Comment by AriaElidove** [comment] 2023-12-05 05:21
It doesn't seem to be affecting other dimension mods (Tested Aether and Voidscape mods' respective dimensions, works completely fine).

Will do Tama.

**Comment by thexaero** [comment] 2023-12-05 14:47
The issue is on my end. Currently fixing it.

**Comment by GizmoTheMoonPig** [comment] 2023-12-11 06:42
looks like this is fixed in the newest versions of Xaero's

**Closed as completed by GizmoTheMoonPig** 2023-12-11 06:42 UTC
Labels: bug
