### ISSUE TITLE
Water leaks in multiple structures

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1043] opened 2021-04-05 19:45 UTC
![image](https://user-images.githubusercontent.com/36087299/113618606-ec755180-9625-11eb-9924-2ca42cffc024.png)

**Comment by SatDog92** [comment] 2021-04-06 09:17
Instead of opening another issue i want to add this info in here instead: this happens with lava too:

[Lava burning everything](https://user-images.githubusercontent.com/56725716/113687276-74139c80-96c8-11eb-9db6-2c59c1d09bf3.png);
[Lava pouring from the floating tower](https://user-images.githubusercontent.com/56725716/113687281-7544c980-96c8-11eb-8021-3ec54c423ece.png).

Maybe this was intended but... this destroys the architecture.

**Comment by Tamaized** [comment] 2021-05-30 18:31
This needs to rechecked as it was most likely fixed by my structure aware feature placement code but that's only an assumption. If someone can verify that'd be excellent.

**Comment by EvergreenSystems** [comment] 2021-05-30 18:31
I have not seen that since your structure fix, I'll keep an eye out for it in the future

**Comment by GizmoTheMoonPig** [comment] 2021-06-16 06:11
I havent seen this issue occur anymore, so im gonna close it. Feel free to open it if you notice it still happening.

**Closed as completed by GizmoTheMoonPig** 2021-06-16 06:11 UTC
Labels: bug
