### ISSUE TITLE
[1.12.2] SP Hosted LAN Players don't receive advancements correctly

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#344] opened 2017-11-19 22:53 UTC
Forge version: 2537
Twilight Forest version: 3.3.202
Link to crash log: 

Steps to reproduce:
1. LAN Players join hosted game on SP and travel through a TW portal.
2. TW Advancements do not update for those players at all or update erratically.

What I expected to happen:
Players gain advancements along with or when they do the required steps.

There really needs to be a way to either give advancements to players via commands or turn off area progression.

**Comment by Andromander** [comment] 2017-11-19 22:56
Addressed in #176. It is possible to completely disable progression with `tfEnforcedProgression`, but that affects every area progression and cannot be used selectively

**Comment by MokahTGS** [comment] 2017-11-19 23:05
So I can turn it off completely?

**Comment by Andromander** [comment] 2017-11-19 23:06
Yes. Using `/gamerule tfEnforcedProgression false` will disable progression

**Comment by Drullkus** [comment] 2017-11-19 23:32
I'd to investigate this issue still.

**Comment by MokahTGS** [comment] 2017-11-19 23:38
Do you need more data from us?

**Comment by Drullkus** [comment] 2017-11-20 08:35
Nah

**Comment by Tamaized** [comment] 2019-05-09 22:37
Is this still an issue in the latest builds? As I can't reproduce.

**Comment by Drullkus** [comment] 2021-09-03 04:54
Probably fixed in newer versions of Minecraft

**Closed as completed by Drullkus** 2021-09-03 04:54 UTC
Labels: progression
