### ISSUE TITLE
Stairs in Final Castle don't face the correct way

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1053] opened 2021-04-06 20:03 UTC
![image](https://user-images.githubusercontent.com/36087299/113771671-ae456400-96f1-11eb-9f71-42526eda468b.png)

**Comment by GizmoTheMoonPig** [comment] 2021-04-06 20:04
duplicate of #1036

**Closed as completed by GizmoTheMoonPig** 2021-04-06 20:04 UTC
