### ISSUE TITLE
Twilight Forest 3.9.851 crashes upon attempting to launch with Forge version 14.23.5.2807

### ISSUE THREAD

**Issue by ALPHANUMERIC1** [TeamTwilight/twilightforest#691] opened 2019-01-18 04:41 UTC
Forge version: 14.23.5.2807
Twilight Forest version: (3.9.851)
Link to crash log: [https://gist.github.com/ALPHANUMERIC1/dd9692c3dab402d08858e1efcb5d531b](https://gist.github.com/ALPHANUMERIC1/dd9692c3dab402d08858e1efcb5d531b)

Steps to reproduce:
1. Attempt to launch the game

What I expected to happen: I expected to be able to launch the game

What happened instead: The game crashed

**Comment by Andromander** [comment] 2019-01-18 04:45
Duplicate of #685. This is caused by JEID.

**Closed as completed** 2019-01-18 12:35 UTC
Labels: duplicate

**Comment by ALPHANUMERIC1** [comment] 2019-01-19 04:41
Thanks.
