### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by szunakabeats** [TeamTwilight/twilightforest#1373] opened 2021-11-04 11:06 UTC
### Forge Version

36.2.0

### Twilight Forest Version

1.16.5-4.0.546

### Client Log

https://gist.github.com/szunakabeats/4076b33354b643a929995cc6ac63a357

### Steps to Reproduce

1. Install "Twilight Forest" and "Just Enough Items"
2. Create a World and in JEI search for @twilight
3. Scroll through the different items and you will find Pink and Black Textures
4. For Example the Oak Door

### What You Expected

Having textures like any other Twilight Forest Item

### What Happened Instead

Pink and Black square textures appearing in JEI's list.

### Additional Details

[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:twilight_oak_door#inventory' referenced from: twilightforest:twilight_oak_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/twilight_oak_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:canopy_door#inventory' referenced from: twilightforest:canopy_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/canopy_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:mangrove_door#inventory' referenced from: twilightforest:mangrove_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/mangrove_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:dark_door#inventory' referenced from: twilightforest:dark_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/dark_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:time_door#inventory' referenced from: twilightforest:time_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/time_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:trans_door#inventory' referenced from: twilightforest:trans_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/trans_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:mine_door#inventory' referenced from: twilightforest:mine_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/mine_door.json
[12:02:15] [Worker-Main-11/WARN]: Unable to load model: 'twilightforest:sort_door#inventory' referenced from: twilightforest:sort_door#inventory: java.io.FileNotFoundException: twilightforest:models/item/sort_door.json
[12:02:15] [Worker-Main-12/ERROR]: Using missing texture, unable to load twilightforest:textures/block/wood/door/trans_lower.png : java.io.IOException: Could not read info from the PNG file net.minecraft.resources.SimpleResource@46e271d9 Image not of any known type, or corrupt
[12:02:15] [Worker-Main-13/ERROR]: Using missing texture, unable to load twilightforest:textures/block/wood/door/trans_upper.png : java.io.IOException: Could not read info from the PNG file net.minecraft.resources.SimpleResource@72dfe6fa Image not of any known type, or corrupt
[12:02:15] [Worker-Main-12/ERROR]: Using missing texture, unable to load twilightforest:textures/block/wood/trapdoor/trans_trapdoor.png : java.io.IOException: Could not read info from the PNG file net.minecraft.resources.SimpleResource@f5006e24 Image not of any known type, or corrupt
[12:02:17] [Render thread/WARN]: Missing sound for event: twilightforest:entity.twilightforest.termite.twilightforest.ambient
[12:02:17] [Render thread/WARN]: Missing sound for event: twilightforest:entity.twilightforest.termite.twilightforest.death
[12:02:17] [Render thread/WARN]: Missing sound for event: twilightforest:entity.twilightforest.termite.twilightforest.hurt
[12:02:17] [Render thread/WARN]: Missing sound for event: twilightforest:entity.twilightforest.termite.twilightforest.step

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment] 2021-11-04 11:32
Duplicate of #711, fixed in 170175650c94ac835a90b925c3a65d0c28954d41

**Closed as completed by Drullkus** 2021-11-04 11:32 UTC
Labels: bug, duplicate, shut

**Comment by szunakabeats** [comment] 2021-11-04 11:57
so it's fixed in 1.17.x and not in 1.16.x ?

**Comment by EvergreenSystems** [comment] 2021-11-04 14:24
Correct
