### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Omnimetatron** [TeamTwilight/twilightforest#630] opened 2018-09-22 21:12 UTC
Forge version:  14.23.4.2755
Twilight Forest version: 3.8.689
Link to crash log: https://pastebin.com/eAyVuees

Steps to reproduce:
1. Was exploring, have killed Naga and Lich, went into a hill to do some mining then crashed. Just loading up the game crashes to desktop now.

What I expected to happen: The game not to crash

What happened instead: The game crashed

**Comment by Andromander** [comment] 2018-10-08 10:18
I don't quite fully understand crash logs where the error is `ConcurrentModificationException`, however, the stacktrace leads back to something relating to sounds. After some digging around, it could be caused by the mod Sound Filters, though this may be speculation.

**Comment by Andromander** [comment] 2021-05-25 10:54
Closing as the problem doesn't appear in the mod. If this still occurs, feel free to reopen this, as well as verify if another mod may be the cause.

**Closed as completed by Andromander** 2021-05-25 10:54 UTC
