### ISSUE TITLE
Crash with terraqueous trees

### ISSUE THREAD

**Issue by evhub** [TeamTwilight/twilightforest#474] opened 2018-04-15 07:50 UTC
Forge version: 1.12.2-14.23.2.2646
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: https://gist.github.com/evhub/7792ddeebb2857dc8b287567496e5bc0

Steps to reproduce:
1. have terraqueous tree generation enabled,
2. explore in the twilight forest.

From a cursory inspection of the crash report, this looks like a twilight forest problem, since it seems to be that twilight forest is expecting only a certain set of tree types and is finding something outside that set, but feel free to close this if you don't think it's a bug with twilight forest. It's also possible I'm misdiagnosing this crash as a twilight forest-terraqueous incompatibility when it's not that at all.

**Comment by Andromander** [comment] 2018-04-15 07:52
Should be fixed in 44d42b0, but not officially released yet. Also a duplicate of #472.

**Comment by Tamaized** [comment] 2018-04-15 16:09
^

**Closed as completed by Tamaized** 2018-04-15 16:09 UTC
