### ISSUE TITLE
Medium Hollow Hills Gen Too High

### ISSUE THREAD

**Issue by Lonemind** [TeamTwilight/twilightforest#1513] opened 2022-06-05 18:07 UTC
### Forge Version

40.1.31

### Twilight Forest Version

4.1.1052

### Steps to Reproduce

Fly around Twilight Forest and let Medium Hollow Hills generate.

### What You Expected

Hollow hill should be attached to the ground.

### What Happened Instead

It appears that the medium hollow hill is generating four or five blocks too high. The bowl of space it generates underneath it is not attached to the stalagmites rising from the ground. I attached a screenshot of a crosscut of the medium hollow hill. It explains better than words.

### Additional Details

https://imgur.com/a/XzXREC4

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2022-06-05 19:00
Duplicate of #1504, already been fixed

**Closed as completed by GizmoTheMoonPig** 2022-06-05 19:00 UTC
Labels: bug
