### ISSUE TITLE
Portal spawning under water in Twilight Lake biome

### ISSUE THREAD

**Issue by LemADEC** [TeamTwilight/twilightforest#481] opened 2018-04-27 21:40 UTC
Forge version: 14.23.3.2655
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: n/a

Steps to reproduce:
1. generate a portal in the overworld
2. jump into the portal

What I expected to happen:
portal is at the surface in a safe place

What happened instead:
portal was 1 block under water in a TwilightLake biome, with portal Y = 29

![image](https://user-images.githubusercontent.com/4776032/39386242-0020b8c4-4a74-11e8-8cdd-8362a0148f40.png)

This is on a public server using FTB direwolf20 1.12 version 1.10.0

**Comment by Tamaized** [comment] 2018-04-30 18:47
actually a duplicate of #465

**Closed as completed by Tamaized** 2018-04-30 18:47 UTC
Labels: bug
