### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by walker-dev** [TeamTwilight/twilightforest#466] opened 2018-04-01 05:52 UTC
Forge version: 14.23.2.2640
Twilight Forest version: (3.6.372)
Link to crash log: [crash-2018-04-01_07.42.38-server.txt](https://gist.githubusercontent.com/boosterdev/2e6ccd69336d6121fc8238eb10e40628/raw/)

Steps to reproduce:
1. install on server.

**Comment by Andromander** [comment] 2018-04-01 05:55
Likely a duplicate of #464 except this is the result on the Server

**Comment by walker-dev** [comment] 2018-04-01 05:57
not really, tinkers construct is installed

**Comment by Tamaized** [comment] 2018-04-01 06:14
It's not a duplicate

**Comment by walker-dev** [comment] 2018-04-01 06:14
this happends on build 370 allready, 369 is ok

**Comment by Andromander** [comment] 2018-04-01 06:17
Sounds about right. The error seems to be occurring because of the fluids, for some reason.

**Comment by Tamaized** [comment] 2018-04-19 20:53
Should be fixed by 8be6385bd32648d8ee6a32b7f1eb15cd526b4fb8

**Closed as completed by Tamaized** 2018-04-19 20:53 UTC
Labels: bug
