### ISSUE TITLE
Server crashes when any entity enters the portal (Multiplayer Only)

### ISSUE THREAD

**Issue by Lorgelran** [TeamTwilight/twilightforest#589] opened 2018-08-03 14:48 UTC
Forge version: forge-1.12.2-14.23.4.2746-universal
Twilight Forest version: 3.7.424
[crash log](https://gist.github.com/Lorgelran/00ff61e49d3772e41dd85858715891a4)

Steps to reproduce:
1. Run a forge server with using [this modpack](https://www.technicpack.net/modpack/lydias-dimensional-pack.1278328).
2. Build a portal to the twilight forest.
3. Enter the portal.

What I expected to happen:
I expected to enter the Twilight Forest successfully as so happens in singleplayer.

What happened instead:
The server crashes when any entity enters the portal, giving users a "Timed Out" error message. This happened on two different PCs. What is particularly confusing is that the mod and the modpack all work perfectly in singleplayer.

**Comment by Tamaized** [comment] 2018-08-03 20:33
Duplicate of #371
Your server exceeded the max tick time on a single tick defined in your server.properties file

**Closed as completed by Tamaized** 2018-08-03 20:33 UTC
Labels: duplicate
