### ISSUE TITLE
Portals are not linked to each other

### ISSUE THREAD

**Issue by SoldierKucha** [TeamTwilight/twilightforest#891] opened 2020-06-07 16:00 UTC
Forge version: 14.23.5.2847
Twilight Forest version: 1.12.2 - 3.10.1013
Link to crash log:

Steps to reproduce:
1. Create a portal
2. Enter the portal
3. Exit the portal

What I expected to happen: Exit from the same portal i entered

What happened instead: Exiting creates a new portal on different coordinates, somewhere near 400:20

**Comment by Alyaqdhans** [comment] 2020-06-08 02:56
Try installing (NetherPortalFix) maybe it will fix it?

**Comment by SoldierKucha** [comment] 2020-06-08 04:54
I do have it. Will try without it later

**Comment by SoldierKucha** [comment] 2020-06-08 11:27
Disabling it fixed nothing, but after some testing VanillaFix pointed in BetterPortals direction. Gonna dig from there now.

**Comment by bs2609** [comment] 2020-06-08 12:09
This sounds like a duplicate of #617, refer to the instructions in that thread.

**Comment by SoldierKucha** [comment] 2020-06-08 12:48
Should i Enable it? Cause in my cfg it is set to False

**Comment by SoldierKucha** [comment] 2020-06-08 13:48
![2020-06-08_16 44 28](https://user-images.githubusercontent.com/15803655/84037882-df58e900-a9a7-11ea-973c-8a4eac9ec3a7.png)
Here's a picture of a map

**Comment by SoldierKucha** [comment] 2020-06-08 13:50
What exactly I should do next?

**Comment by SoldierKucha** [comment] 2020-06-08 14:30
Ok, i think i did it right. I made a portal at the TF where i spawned using command. Strange that its underground, somewhere what is NYI.

**Closed as completed** 2020-06-09 06:47 UTC
Labels: duplicate
