### ISSUE TITLE
Twilight Crash Swamp Spider Error

### ISSUE THREAD

**Issue by lordcooler13** [TeamTwilight/twilightforest#690] opened 2019-01-17 15:08 UTC
Forge version: 
Twilight Forest version: MC 1.12.2 - 3.8.689
Link to crash log: https://paste.feed-the-beast.com/view/28ff587a

Steps to reproduce:
1. Enter Twlight few secs to few minutes crash cause of swamp spider

What I expected to happen:   Not crash ;p

What happened instead: Crashed

Comment: I seen some related issues but no fix yet since use direwolf20 1.12 with twilight and use server paid server to load it.

**Comment by bs2609** [comment] 2019-01-17 15:09
Duplicate of #660

**Closed as completed by bs2609** 2019-01-17 15:09 UTC
Labels: duplicate
