### ISSUE TITLE
Structure placement creating crash on server

### ISSUE THREAD

**Issue by Annabellechu** [TeamTwilight/twilightforest#1726] opened 2023-01-15 02:47 UTC
### Forge Version

43.2.3

### Twilight Forest Version

4.2.1468

### Crash Report (if applicable)

https://mclo.gs/8OgZEOe

### Steps to Reproduce

1. Log on with an account where the problem initially was
2. Server crashes

If anyone else or said player doesn't log in the twilight forest the problem does not happen
Temporary fix - /cu unstuck <player> forcing them to spawn point

### What You Expected

Server not to crash

### What Happened Instead

Server crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-01-15 02:49
duplicate of #1699

**Closed as completed by GizmoTheMoonPig** 2023-01-15 02:49 UTC
Labels: bug
