### ISSUE TITLE
I have this problem with my minecraft server

### ISSUE THREAD

**Issue by Ab3lGames** [TeamTwilight/twilightforest#840] opened 2019-12-03 18:18 UTC
Minecraft 1.12.2  Forge: 14.23.5.2838
Twilight Forest version: twilightforest-1.12.2-3.9.984-universal.jar ( I tried with the last version but is the same problem.) 
Link to crash log: https://pastebin.com/MGUvENzR

Steps to reproduce:
I'm just playing and my server close.

What happened instead:
My server close.

**Comment by Killer-Demon** [comment] 2021-05-25 03:44
Duplicate of #875 which was closed as it does not crash in 1.16.5 with only Twilight Forest installed.

**Closed as completed by Killer-Demon** 2021-05-25 03:44 UTC
