### ISSUE TITLE
(1.12.2) Darkwood leaves not disintegrating

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#974] opened 2020-10-31 05:25 UTC
Forge version: 8.0.99.99
Twilight Forest version: 3.11.1021
Link to crash log: (no crash)

Steps to reproduce:
1. Chop down a Darkwood tree, clear it of all wood.
1a (optional): Use the Tree Chopper mod for a more clear, visual example.

What I expected to happen:
I expected the leaves to break like normal, and even drop either themselves with Shears, or if broken if anything else, saplings.

What happened instead:
The leaf blocks wouldn't disintegrate like normal. It takes much longer to break them. It wouldn't burn up if a flint and steel or lava are being used. They wouldn't even drop themselves if shears are used. Interestingly, saplings would still be produced if the Tree Chopper mod is used.

EDIT: Even weirder, they can drop the saplings if planting other trees where the leaves are.

**Comment by bs2609** [comment] 2021-04-27 00:08
I believe the leaves not decaying like normal leaves is by design - for performance reasons.
The drops are a different issue that might need looking at.

**Comment by Andromander** [comment] 2021-05-25 11:32
Resolved in 1.16. The non-decaying leaves are a feature as to save performance, and they drop as they should, with and without Shears.

**Closed as completed by Andromander** 2021-05-25 11:32 UTC
