### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#727] opened 2019-04-03 19:39 UTC
that's because of twilight forest right?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  EmoticonsCore (emoticons-0.2-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 4/3/19 9:34 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_TFEntities_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:415)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:286)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:271)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:256)
	at net.minecraftforge.common.util.EnumHelper.addSpawnPlacementType(EnumHelper.java:156)
	at twilightforest.entity.TFEntities.<clinit>(TFEntities.java:31)
	... 16 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.common.util.EnumHelper.getConstructorAccessor(EnumHelper.java:207)
	at net.minecraftforge.common.util.EnumHelper.makeEnum(EnumHelper.java:220)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:406)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_TFEntities_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 515831032 bytes (491 MB) / 1073741824 bytes (1024 MB) up to 27917287424 bytes (26624 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx26G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E2 41 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version           | Source                                        | Signature                                |
	|:----- |:-------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCH   | mcp            | 9.42              | minecraft.jar                                 | None                                     |
	| UCH   | FML            | 8.0.99.99         | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.5.2772      | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | simplecore     | 1.7.3.4           | simplecore-1.12.2-1.7.3.4.jar                 | None                                     |
	| UCH   | simpleores     | 1.11.2.2          | simpleores-1.12.2-1.11.2.2.jar                | None                                     |
	| UCH   | netherrocks    | 1.7.1.2           | netherrocks-1.12.2-1.7.1.2.jar                | None                                     |
	| UCH   | fusion         | 2.4.1.11          | fusion-1.12.2-2.4.1.11.jar                    | None                                     |
	| UCH   | aesthetics     | 1.6.0.23          | aesthetics-1.12.2-1.6.0.23.jar                | None                                     |
	| UCH   | biomesoplenty  | 7.0.1.2402        | BiomesOPlenty-1.12.2-7.0.1.2402-universal.jar | None                                     |
	| UCH   | baubles        | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCH   | botania        | r1.10-357         | Botania+r1.10-357.jar                         | None                                     |
	| UCH   | craftstudioapi | 1.0.0             | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UCH   | ctm            | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar                     | None                                     |
	| UCH   | twilightforest | 3.9.888           | twilightforest-1.12.2-3.9.888-universal.jar   | None                                     |
	| UCH   | animania       | 1.6.0.2           | animania-1.12.2-1.6.0.2.jar                   | None                                     |
	| UCH   | autoreglib     | 1.3-20            | AutoRegLib-1.3-20.jar                         | None                                     |
	| UCH   | forgelin       | 1.8.0             | Forgelin-1.8.0.jar                            | None                                     |
	| UCH   | betterfoliage  | 2.2.0             | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
	| UCH   | bullseye       | 3.0.6             | Bullseye-1.12.2-3.0.6.jar                     | None                                     |
	| UCH   | chisel         | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| UCH   | embers         | 0.230             | embers-0.230.jar                              | None                                     |
	| UCH   | emoticons      | 0.2               | emoticons-0.2-1.12.2.jar                      | None                                     |
	| UCH   | familiarfauna  | 1.0.10            | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
	| UCH   | grue           | 1.4.0             | Grue-1.12.2-1.4.0.jar                         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | llibrary       | 1.7.15            | llibrary-1.7.15-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | iceandfire     | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
	| UCH   | inventorypets  | 1.5.3.1           | inventorypets-1.12-1.5.3.1.jar                | None                                     |
	| UCH   | ironchest      | 1.12.2-7.0.52.837 | ironchest-1.12.2-7.0.52.837.jar               | None                                     |
	| UCH   | journeymap     | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| UCH   | lex            | 1.0.8             | LibEx-1.12.2-1.0.8.jar                        | None                                     |
	| UCH   | machines       | 1.3.0.8           | machines-1.12.2-1.3.0.8.jar                   | None                                     |
	| UCH   | mantle         | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                      | None                                     |
	| UCH   | nex            | 2.0.8             | NetherEx-1.12.2-2.0.8.jar                     | None                                     |
	| UCH   | roguelike      | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| UCH   | roots          | 0.104             | roots-2-0.104.jar                             | None                                     |
	| UCH   | sereneseasons  | 1.2.6             | SereneSeasons-1.12.2-1.2.6-universal.jar      | None                                     |
	| UCH   | tconstruct     | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar              | None                                     |
	| UCH   | toughasnails   | 3.1.0.129         | ToughAsNails-1.12.2-3.1.0.129-universal.jar   | None                                     |
	| UCH   | warpbook       | @VERSION@         | Warp-Book-Mod-1.12.2.jar                      | None                                     |
	| UD    | emoticons_core | 0.2               | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
EmoticonsCore (emoticons-0.2-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.73' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.73, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

**Comment by bs2609** [comment] 2019-04-03 21:34
Duplicate of #686

**Closed as completed by bs2609** 2019-04-03 21:34 UTC
Labels: duplicate
