### ISSUE TITLE
server crashed when walking near a final castle.

### ISSUE THREAD

**Issue by Viola-Siemens** [TeamTwilight/twilightforest#1739] opened 2023-02-03 14:06 UTC
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1493-universal

### Client Log

https://gist.github.com/Viola-Siemens/5de46e6d78458af70170d0480be70002

### Crash Report (if applicable)

https://gist.github.com/Viola-Siemens/29163fd13b0076c9ac77feadd5cec200

### Steps to Reproduce

It may be hard to reproduce, the only thing I record is the seed of the server and which position the server-crasher stands on.

seed: 1192581504539931708

position in twilight forest: (-4450, 7, -1771)

### What You Expected

I have already modify the NBT of the player to stay away from that chunk. So if this is a bug, you can choose to fix it in future versions, or release a new version for 1.19.2.

### What Happened Instead

If this is not a bug, that's my bad. I really enjoy your mod.

### Additional Details

It seems that you use a zero or negative value as the parameter of RandomSource.nextInt(int bound)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-02-03 14:23
Duplicate of #1699

**Closed as completed by GizmoTheMoonPig** 2023-02-03 14:23 UTC
Labels: bug
