### ISSUE TITLE
The TF Portal Issue List

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1459] opened 2022-03-23 02:58 UTC
Twilight Forest portals currently have quite a few issues, and I think it would be good to have a singular issue that describes all of the issues people have with them for easier fixing later. **Please comment more issues if you don't see them here!** 

Current known issues:
- Portals will sometimes attempt to spawn in locked biomes, and that's not a good thing. We try to redirect portals out of these locked biomes and into safe ones. However, portal redirection sometimes puts portals really far from where they would originally go. This leads to a couple issues:
  - Returning from TF will create a new portal, often really far from your original. 
  - Re-entering TF from the original portal will spawn a new portal, often times in a locked biome.
- If a portal attempts to spawn in the thornlands/plateau, it will spawn underground in a small box.

**Comment by Tamaized** [comment] 2022-03-23 02:59
Spawning in locked biomes happens when the teleporter fails to find a safe area

**Comment by Tamaized** [comment] 2022-03-23 03:04
One thing to think about is we know where Key Biomes generally are in a 2048x Magic Map space. We can use this to our advantage and precalculate Teleporters to move towards the center of a Magic Map area before running all the safety checks.

**Comment by SodiumZH** [comment] 2022-08-28 08:07
The portal may also generate inside a Naga Courtyard.

**Comment by PraseodymiumSpike** [comment] 2022-09-14 00:05
I have a portal on the Official Twilight Forest Server that links to a body of Water in the Overworld. If you go into the portal, and there isn't one on the other side, it sometimes drops you into the Water without generating a return portal in the same spot. This isn't a big issue as I have a return portal nearby, but I thought it was worth mentioning. Note that I find the return portal in the middle of the Water ugly, so I usually break it if it spawns when I go through. If the portal in the water was still there, presumably, it would work as intended.

**Comment by SodiumZH** [comment] 2022-09-14 05:27
> I have a portal on the Official Twilight Forest Server that links to a body of Water in the Overworld. If you go into the portal, and there isn't one on the other side, it sometimes drops you into the Water without generating a return portal in the same spot. This isn't a big issue as I have a return portal nearby, but I thought it was worth mentioning. Note that I find the return portal in the middle of the Water ugly, so I usually break it if it spawns when I go through. If the portal in the water was still there, presumably, it would work as intended.

Usually it works correctly as you say, but sometimes (see #1613) some unexpected random cases may occur. For example, when you go into a manually-created portal in TF, it generates a portal in the Overworld; but sometimes when you attempt to go back, the generated portal will drop you to another point, creating another portal in the TF. Repeating the operations above will even generate several random portals. If a portal drop the player always to the same point, in my opinion, it may be not a serious issue; but randomly dropping the player to unknown places is probably a problem.

**Comment by Thunderrock424242** [comment] 2023-01-26 21:06
is this ever gonna be fixed in 1.16.5?

**Comment by GizmoTheMoonPig** [comment] 2023-01-26 21:16
1.16 is no longer receiving updates. This will be fixed in whatever version we're able to get to it

**Comment by Tamaized** [comment] 2023-02-06 19:43
Portals will now retain links on world restarts
e44f07dce7a8e73a1da1552addd9540c847950a2

Portals no longer spawn inside of structures when the dimension is first generated from traveling through the portal for the first time
2b5cd9ea49828501d4a4759f84dbc61ac5bd7e23

**Comment by Tamaized** [comment] 2023-02-06 20:24
Actually after closer investigation it turns out linkage is COMPLETELY BROKEN.

I've discovered that wrong block positions are being passed around all over the place.

Handled in 9e4f5feb40554997e94d383c89dcf6f8aab5892f, needs testing however.

**Comment by Tamaized** [comment] 2023-02-08 04:52
Teleporters now move towards the center of a magic map area as needed.
f8e4a387fd6150f762235b97b29f83d6fb7d5cfa

**Comment by Tamaized** [comment] 2023-02-09 16:08
I've ironed out every thing I can think of with portal problems. I believe I can safely close this now.

**Closed as completed by Tamaized** 2023-02-09 16:08 UTC
Labels: bug, priority-high

**Comment by AnkarraKM** [comment] 2023-03-21 09:43
My Portal spawns in a restricted area. I play in the  1.19.3 version. Is there something I can do to fix this or will I have to move the portal?

Thanks in advance.

**Comment by mapyDayton22** [comment] 2024-05-06 14:16
I made a portal and I went through it and entered the Twilight Forest. When I went back through the portal, it sends me 1000 blocks away from my original portal.

**Comment by TheTrueFury** [comment] 2025-05-24 14:04
> I made a portal and I went through it and entered the Twilight Forest. When I went back through the portal, it sends me 1000 blocks away from my original portal.

Just got this same issue on "twilightforest-1.20.1-4.3.1893-universal.jar". Except I was sent about 9k blocks away.

Edit:  I was also underground at Y=0, inside blocks.
