### ISSUE TITLE
Pinch bettles still consume your hotbar after the apperent fix

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1332] opened 2021-10-04 21:41 UTC
### Forge Version

37.0.73

### Twilight Forest Version

4.0.742

### Steps to Reproduce

step 1: get kidnapped by a pinch bottle
step 2: suffer

### What You Expected

hotbar

### What Happened Instead

no hotbar

### Additional Details

it was stated that this bug was fixed along side the ur ghast tower crash in the server announcements, but it still happens, don't know if the fix didn't work of he just didn't apply the fix

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment] 2021-10-04 21:51
this was fixed in TF 4.0.743, (which I posted in the announcements) try updating to that first and then get back to me about it

**Comment by VilligerKing** [comment] 2021-10-04 22:41
ight so im half right, it only consumes my hunger bar now, but I suggest you test it for yourself, bc if its fine for you, its an incompatibility w apple skin (science appleskin messes w the hunger bar and is the only mod I have that does so) aka on my side

**Comment by VilligerKing** [comment] 2021-10-04 22:42
also this was after updating bc i hadn't updated :p

**Comment by GizmoTheMoonPig** [comment] 2021-10-04 23:31
so the reason it gets rid of your hunger bar is because normally the mount health is put in that location when riding an entity. We hide the mount health when riding a hostile such as a yeti or pinch beetle. I can see if I can force the hunger bar to be back there, but im not sure if its doable or not 

So in essence, its intended but we might be able to change it

**Comment by VilligerKing** [comment] 2021-10-05 11:27
Now that I think about it, why not show the bettles health? When you think about it, showing the nettles health whould not only be simpler to do, but also create am interesting situation when you are grabbed by a bottle, it whould be a race against health bars to see which one reaches 0, and considering how many times I've been left on half a heart on my late game armour, I think it's fair to say that beating the battle race whould give the player a feeling of accomplishment 

(Side note tho, if this were to happen, I whould also have the bottle health have a different texture than normal rideable animals, cause ya know)

**Comment by GizmoTheMoonPig** [comment] 2022-05-25 15:18
works as intended for now. The last bit of this became a suggestion which im not exactly interested in implementing at the moment, but i'll keep it mind. Thanks for the idea!

**Closed as completed by GizmoTheMoonPig** 2022-05-25 15:18 UTC
Labels: bug
