### ISSUE TITLE
Hydra Lair Missing/Broken

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1258] opened 2021-08-29 14:27 UTC
Forge version: 1.17.1 modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

i dont really have any words for this, but the hydra lair is completely broken/missing in some areas. and in other areas, its misleved.

![2021-08-29_08 15 03](https://user-images.githubusercontent.com/68449401/131253831-37b9b351-7d44-4a0f-945f-2da47c429742.png)

**Comment by Drullkus** [comment] 2021-08-29 19:58
I’ve seen this about 4 times in development and it’s looked perfectly fine. You’ll need to give me seed and coordinates

**Comment by CobaltGlacier** [comment] 2021-08-31 00:13
i have no idea where those coords are. i traveled like 20,000 blocks or so in that world

**Comment by Drullkus** [comment] 2021-08-31 00:15
I figured out the cause of the problem anyway, no need to

**Comment by CobaltGlacier** [comment] 2021-08-31 00:18
alright, thanks for taking care of this

**Comment by Drullkus** [comment] 2021-10-19 02:39
Fixed via 3cfc50ab531349fe7e76ce1171786fdecb6e0338

**Closed as completed by Drullkus** 2021-10-19 02:39 UTC
Labels: bug
